In [2]:
import pandas as pd
import os

In [44]:
vdjdb = pd.read_csv('./vdjdb/vdjdb.txt', sep='\t',)
vdjdb

,complex.id,gene,cdr3,v.segm,j.segm,species,mhc.a,mhc.b,mhc.class,antigen.epitope,...,vdjdb.score,TCR_hash,method,meta,cdr3fix,web.method,web.method.seq,web.cdr3fix.nc,web.cdr3fix.unmp,vdjdb.pgen.score
0,0,TRB,CASSIVGGNEQFF,TRBV19*01,TRBJ2-1*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,...,3,NaN,"{""identification"": ""tetramer-sort "", ""frequenc...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSIVGGNEQFF"", ""cdr3_old"": ""CASSIVG...",sort,amplicon,no,no,2
1,0,TRB,CASSMRSTGELFF,TRBV19*01,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,...,3,NaN,"{""identification"": ""tetramer-sort "", ""frequenc...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSMRSTGELFF"", ""cdr3_old"": ""CASSMRS...",sort,amplicon,no,no,2
2,0,TRB,CASSIRSAWAQYF,TRBV19*01,TRBJ2-3*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,...,2,NaN,"{""identification"": ""tetramer-sort "", ""frequenc...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSIRSAWAQYF"", ""cdr3_old"": ""CASSIRS...",sort,amplicon,no,no,2
3,0,TRB,CASSQRSTGELFF,TRBV19*01,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,...,2,NaN,"{""identification"": ""tetramer-sort "", ""frequenc...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSQRSTGELFF"", ""cdr3_old"": ""CASSQRS...",sort,amplicon,no,no,3
4,0,TRB,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,MHCI,GILGFVFTL,...,3,NaN,"{""identification"": ""tetramer-sort "", ""frequenc...","{""study.id"": """", ""cell.subset"": ""CD8+"", ""subje...","{""cdr3"": ""CASSIRSSYEQYF"", ""cdr3_old"": ""CASSIRS...",sort,amplicon,no,no,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226489,0,TRB,CASSPSARGNQPQHF,TRBV2*01,TRBJ1-5*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,MHCII,FRDYVDRFYKTLRAEQASQE,...,0,NaN,"{""identification"": ""cultured-T-cells,tetramer-...","{""study.id"": """", ""cell.subset"": ""CD4+"", ""subje...","{""cdr3"": ""CASSPSARGNQPQHF"", ""cdr3_old"": ""CASSP...",sort,sanger,no,no,2
226490,0,TRB,CASSVGTSGVGEQYF,TRBV2*01,TRBJ2-7*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,MHCII,FRDYVDRFYKTLRAEQASQE,...,0,NaN,"{""identification"": ""cultured-T-cells,tetramer-...","{""study.id"": """", ""cell.subset"": ""CD4+"", ""subje...","{""cdr3"": ""CASSVGTSGVGEQYF"", ""cdr3_old"": ""CASSV...",sort,sanger,no,no,2
226491,0,TRB,CASSALASGGDTQYF,TRBV2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,MHCII,FRDYVDRFYKTLRAEQASQE,...,0,NaN,"{""identification"": ""cultured-T-cells,tetramer-...","{""study.id"": """", ""cell.subset"": ""CD4+"", ""subje...","{""cdr3"": ""CASSALASGGDTQYF"", ""cdr3_old"": ""CASSA...",sort,sanger,no,no,2
226492,0,TRB,CASSRLAGGMDEQFF,TRBV2*01,TRBJ2-1*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,MHCII,FRDYVDRFYKTLRAEQASQE,...,3,NaN,"{""identification"": ""cultured-T-cells,tetramer-...","{""study.id"": """", ""cell.subset"": ""CD4+"", ""subje...","{""cdr3"": ""CASSRLAGGMDEQFF"", ""cdr3_old"": ""CASSR...",sort,sanger,no,no,2
226493,0,TRB,CASSRRTSGGTDTQYF,TRBV2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,MHCII,FRDYVDRFYKTLRAEQASQE,...,2,NaN,"{""identification"": ""cultured-T-cells,tetramer-...","{""study.id"": """", ""cell.subset"": ""CD4+"", ""subje...","{""cdr3"": ""CASSRRTSGGTDTQYF"", ""cdr3_old"": ""CASS...",sort,sanger,no,no,2

In [47]:
vdjdb['meta'].loc[0]

'{"study.id": "", "cell.subset": "CD8+", "subject.cohort": "MA-EBV-SN", "subject.id": "donor1", "replica.id": "", "clone.id": "", "epitope.id": "M158\\u201366", "tissue": "PBMC", "donor.MHC": "A02,A03,B07,B27,C01,C07", "donor.MHC.method": "", "structure.id": "", "samples.found": 2, "studies.found": 1}'

In [28]:
vdjdb = pd.read_csv('./vdjdb/vdjdb_full.txt', sep='\t',)
vdjdb

/scratch/ipykernel_499497/2961392718.py:1: DtypeWarning: Columns (16,19,20,21,22,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  vdjdb = pd.read_csv('./vdjdb/vdjdb_full.txt', sep='\t',)

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,TCR_hash
0,NaN,NaN,NaN,CASSIVGGNEQFF,TRBV19*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIVGGNEQFF', 'cdr3_old': 'CASSIVG...",3,NaN
1,NaN,NaN,NaN,CASSMRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSMRSTGELFF', 'cdr3_old': 'CASSMRS...",3,NaN
2,NaN,NaN,NaN,CASSIRSAWAQYF,TRBV19*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSAWAQYF', 'cdr3_old': 'CASSIRS...",2,NaN
3,NaN,NaN,NaN,CASSQRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSQRSTGELFF', 'cdr3_old': 'CASSQRS...",2,NaN
4,NaN,NaN,NaN,CASSIRSSYEQYF,TRBV19*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSSYEQYF', 'cdr3_old': 'CASSIRS...",3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139739,NaN,NaN,NaN,CASSPSARGNQPQHF,TRBV2*01,TRBD1*01,TRBJ1-5*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSPSARGNQPQHF', 'cdr3_old': 'CASSP...",0,NaN
139740,NaN,NaN,NaN,CASSVGTSGVGEQYF,TRBV2*01,TRBD2*01,TRBJ2-7*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSVGTSGVGEQYF', 'cdr3_old': 'CASSV...",0,NaN
139741,NaN,NaN,NaN,CASSALASGGDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSALASGGDTQYF', 'cdr3_old': 'CASSA...",0,NaN
139742,NaN,NaN,NaN,CASSRLAGGMDEQFF,TRBV2*01,TRBD2*02,TRBJ2-1*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRLAGGMDEQFF', 'cdr3_old': 'CASSR...",3,NaN
139743,NaN,NaN,NaN,CASSRRTSGGTDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRRTSGGTDTQYF', 'cdr3_old': 'CASS...",2,NaN

In [29]:
vdjdb = vdjdb.dropna(subset = 'TCR_hash').drop_duplicates(subset = 'TCR_hash')

In [32]:
vdjdb

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,TCR_hash
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,896916807a877df600fa4a72ad2dca40faba11062e38c8...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,20350288084b42c9b68db20e8e8f90466438e3619b6116...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139153,CAVEDMNSGGYQKVTF,TRAV2*01,TRAJ13*02,CASKRTATYEQYF,TRBV28*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-B*35:01,B2M,...,EPL13B9,EPL,"stem-cell-graft,TCL",HLA-B*35:01,NaN,NaN,"{'cdr3': 'CAVEDMNSGGYQKVTF', 'cdr3_old': 'CAVE...","{'cdr3': 'CASKRTATYEQYF', 'cdr3_old': 'CASKRTA...",3,a8874523e866971fa542d82fba70785d76e7f3fc2eb050...
139155,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,GLC1B4,GLC,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...
139156,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,CLG3A10,CLG,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...
139158,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5B5,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...
139159,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,YVL16D1,YVL,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...

In [23]:
statistics_total = pd.read_csv('./clusters_statisticas_and_contacts/total_res.tsv', sep='\t')
statistics_total

,Unnamed: 0,ranking_confidence,plddt,ptm,iptm,tcr-pmhc_iptm,num_contacts,scanning_angle,pitch_angle
0,fb95e51bc7d7e699457002ecb3cbbc9cce7b1628c37850...,0.545186,88.507215,0.641245,0.521171,0.379790,8.0,74.034401,3.2980
1,5c48c8042cd6405830593d72e1ac3498a24a15a3a4d1d6...,0.609681,90.394358,0.690247,0.589540,0.399869,13.0,62.104000,1.5959
2,4c55d51c798c017d37736929b26903c977a070204f97be...,0.604793,88.812546,0.683908,0.585014,0.452284,18.0,63.183399,4.4731
3,b765d2c65831ba7d99fc49145b7291f56e0f8ca8d4f678...,0.730244,90.659333,0.781723,0.717374,0.706096,20.0,56.415699,4.2708
4,30545cbd3cc0a4290efdbd757c43d9bc20adce5a1a77c1...,0.702323,91.617858,0.762058,0.687389,0.560634,17.0,61.544701,6.9796
...,...,...,...,...,...,...,...,...,...
9799,8d758d286487ce18fd3b2b3d23d796aac6d25d0f4ab926...,0.861143,94.614537,0.885557,0.855039,0.839061,12.0,37.784599,5.7716
9800,c59816afa7843b3ae2093d064da816d743ce973523904f...,0.869992,95.124419,0.892402,0.864390,0.840996,19.0,46.328899,7.1343
9801,f4a15f4197af652eb6a3a8f7557d9776305e3856fecf74...,0.788360,92.823142,0.827428,0.778593,0.689536,18.0,47.352798,3.8434
9802,f78501d4a54031b2a4eacc2b30e8927fea181f42535650...,0.815357,93.252800,0.852147,0.806159,0.765123,22.0,46.741199,3.5940
9803,0ddac88ccd4fb830fd5463344820599395114ca8c18a1e...,0.814281,91.986494,0.845922,0.806371,0.774585,28.0,50.134800,0.4376

In [24]:
statistics_total.rename(columns = {'Unnamed: 0': 'TCR_hash'}, inplace = True)

In [25]:
statistics_total

,TCR_hash,ranking_confidence,plddt,ptm,iptm,tcr-pmhc_iptm,num_contacts,scanning_angle,pitch_angle
0,fb95e51bc7d7e699457002ecb3cbbc9cce7b1628c37850...,0.545186,88.507215,0.641245,0.521171,0.379790,8.0,74.034401,3.2980
1,5c48c8042cd6405830593d72e1ac3498a24a15a3a4d1d6...,0.609681,90.394358,0.690247,0.589540,0.399869,13.0,62.104000,1.5959
2,4c55d51c798c017d37736929b26903c977a070204f97be...,0.604793,88.812546,0.683908,0.585014,0.452284,18.0,63.183399,4.4731
3,b765d2c65831ba7d99fc49145b7291f56e0f8ca8d4f678...,0.730244,90.659333,0.781723,0.717374,0.706096,20.0,56.415699,4.2708
4,30545cbd3cc0a4290efdbd757c43d9bc20adce5a1a77c1...,0.702323,91.617858,0.762058,0.687389,0.560634,17.0,61.544701,6.9796
...,...,...,...,...,...,...,...,...,...
9799,8d758d286487ce18fd3b2b3d23d796aac6d25d0f4ab926...,0.861143,94.614537,0.885557,0.855039,0.839061,12.0,37.784599,5.7716
9800,c59816afa7843b3ae2093d064da816d743ce973523904f...,0.869992,95.124419,0.892402,0.864390,0.840996,19.0,46.328899,7.1343
9801,f4a15f4197af652eb6a3a8f7557d9776305e3856fecf74...,0.788360,92.823142,0.827428,0.778593,0.689536,18.0,47.352798,3.8434
9802,f78501d4a54031b2a4eacc2b30e8927fea181f42535650...,0.815357,93.252800,0.852147,0.806159,0.765123,22.0,46.741199,3.5940
9803,0ddac88ccd4fb830fd5463344820599395114ca8c18a1e...,0.814281,91.986494,0.845922,0.806371,0.774585,28.0,50.134800,0.4376

In [33]:
vdjdb_structures_annotated = vdjdb.merge(statistics_total, on='TCR_hash', how='left')
vdjdb_structures_annotated

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,vdjdb.score,TCR_hash,ranking_confidence,plddt,ptm,iptm,tcr-pmhc_iptm,num_contacts,scanning_angle,pitch_angle
0,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,3,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,896916807a877df600fa4a72ad2dca40faba11062e38c8...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,20350288084b42c9b68db20e8e8f90466438e3619b6116...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,3,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79905,CAVEDMNSGGYQKVTF,TRAV2*01,TRAJ13*02,CASKRTATYEQYF,TRBV28*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-B*35:01,B2M,...,3,a8874523e866971fa542d82fba70785d76e7f3fc2eb050...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79906,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,2,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79907,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,3,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79908,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,3,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79909,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,3,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
vdjdb_structures_annotated.to_csv('vdjdb_structures_annotated.tsv', sep='\t', index=False)

In [43]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime

file_path = 'vdjdb_structures_annotated.tsv'

df = pd.read_csv(file_path, sep='\t', low_memory=False)
has_structure = df['ranking_confidence'].notna()
struct_df = df[has_structure].copy()

total_records = len(df)
num_structures = len(struct_df)
pct = num_structures / total_records * 100

mean_rank = struct_df['ranking_confidence'].mean()
mean_contacts = struct_df['num_contacts'].mean()
mean_scanning = struct_df['scanning_angle'].mean()
mean_pitch = struct_df['pitch_angle'].mean()
corr_angles = struct_df[['scanning_angle', 'pitch_angle']].corr().iloc[0,1]

# Top 15 + Other
epitope_counts = df['antigen.epitope'].value_counts()
top15 = epitope_counts.head(15).index.tolist()

stats_list = []
for epi in top15:
    epi_df = df[df['antigen.epitope'] == epi]
    total = len(epi_df)
    structures = epi_df['ranking_confidence'].notna().sum()
    stats_list.append({
        'Epitope': epi,
        'Total Records': total,
        'Structures': structures,
        '% Structured': round(structures / total * 100, 2) if total > 0 else 0,
        'Mean Ranking Confidence': round(epi_df['ranking_confidence'].mean(), 4) if structures > 0 else None,
        'Mean Contacts': round(epi_df['num_contacts'].mean(), 2) if structures > 0 else None
    })

# Other
other_df = df[~df['antigen.epitope'].isin(top15)]
other_total = len(other_df)
other_struct = other_df['ranking_confidence'].notna().sum()
stats_list.append({
    'Epitope': 'OTHER (rest)',
    'Total Records': other_total,
    'Structures': other_struct,
    '% Structured': round(other_struct / other_total * 100, 2) if other_total > 0 else 0,
    'Mean Ranking Confidence': round(other_df['ranking_confidence'].mean(), 4) if other_struct > 0 else None,
    'Mean Contacts': round(other_df['num_contacts'].mean(), 2) if other_struct > 0 else None
})

stats_df = pd.DataFrame(stats_list)

# Plots with consistent Viridis 0-1 scale
fig_rank = px.histogram(struct_df, x='ranking_confidence', nbins=50, title="Ranking Confidence Distribution")
fig_contacts = px.histogram(struct_df, x='num_contacts', nbins=60, title="Number of Contacts")

fig_epitopes = px.bar(
    stats_df, x='Epitope', y='Structures',
    color='Mean Ranking Confidence',
    color_continuous_scale='Viridis',
    range_color=[0, 1],
    title="Top 15 Epitopes + Other by Number of Structures",
    hover_data=['Total Records', '% Structured', 'Mean Contacts']
)
fig_epitopes.update_layout(xaxis_tickangle=-45, height=650)

# Same palette for scatter plot
fig_angles = px.scatter(
    struct_df, 
    x='scanning_angle', 
    y='pitch_angle', 
    color='ranking_confidence',
    color_continuous_scale='Viridis',   # ← Same as Plot 3
    range_color=[0, 1],                 # ← 0 to 1 scale
    title="Scanning vs Pitch Angle",
    hover_data=['num_contacts', 'antigen.epitope']
)

fig_summary = make_subplots(rows=2, cols=2, subplot_titles=("Ranking Confidence", "Contacts", "Scanning Angle", "Pitch Angle"))
for i, col in enumerate(['ranking_confidence', 'num_contacts', 'scanning_angle', 'pitch_angle']):
    fig_summary.add_trace(go.Histogram(x=struct_df[col], nbinsx=40), row=i//2+1, col=i%2+1)
fig_summary.update_layout(title="All Metrics – Histograms", height=700)

# HTML
html_content = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>🧬 VDJdb Structures Report</title>
    <script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
    <style>
        body {{ font-family: system-ui, Arial, sans-serif; margin: 40px; background: #f8f9fa; }}
        h1, h2 {{ color: #1f2937; }}
        .summary {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 20px; margin: 30px 0; }}
        .card {{ background: white; padding: 20px; border-radius: 12px; box-shadow: 0 4px 12px rgba(0,0,0,0.1); }}
        table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
        th, td {{ padding: 12px; border-bottom: 1px solid #ddd; text-align: left; }}
        th {{ background: #f1f5f9; }}
    </style>
</head>
<body>
    <h1>🧬 VDJdb Structures Annotated – Interactive Report</h1>
    <p>Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Total records: {total_records:,} | Unique epitopes: {df['antigen.epitope'].nunique():,}</p>

    <div class="summary">
        <div class="card"><h3>Records with structures</h3><h2>{num_structures:,} ({pct:.1f}%)</h2></div>
        <div class="card"><h3>Mean ranking confidence</h3><h2>{mean_rank:.4f}</h2></div>
        <div class="card"><h3>Mean contacts</h3><h2>{mean_contacts:.1f}</h2></div>
        <div class="card"><h3>Mean angles</h3><p>Scanning: <strong>{mean_scanning:.1f}°</strong><br>Pitch: <strong>{mean_pitch:.1f}°</strong><br>Corr: <strong>{corr_angles:.3f}</strong></p></div>
    </div>

    <h2>1. Ranking Confidence</h2><div id="rank_plot"></div>
    <h2>2. Number of Contacts</h2><div id="contacts_plot"></div>
    <h2>3. Top 15 Epitopes + Other</h2><div id="epitopes_plot"></div>
    <h2>4. Scanning vs Pitch Angle</h2><div id="angles_plot"></div>
    <h2>5. All Metrics Histograms</h2><div id="summary_plot"></div>

    <h2>Table</h2>
    {stats_df.to_html(index=False, escape=False)}

    <script>
        Plotly.newPlot("rank_plot", {fig_rank.to_json()}, {{responsive: true}});
        Plotly.newPlot("contacts_plot", {fig_contacts.to_json()}, {{responsive: true}});
        Plotly.newPlot("epitopes_plot", {fig_epitopes.to_json()}, {{responsive: true}});
        Plotly.newPlot("angles_plot", {fig_angles.to_json()}, {{responsive: true}});
        Plotly.newPlot("summary_plot", {fig_summary.to_json()}, {{responsive: true}});
    </script>
</body>
</html>
"""

with open('vdjdb_interactive_report_final_consistent.html', 'w', encoding='utf-8') as f:
    f.write(html_content)

print("✅ Report with consistent Viridis 0-1 color scale saved!")

✅ Report with consistent Viridis 0-1 color scale saved!