In [1]:
import pandas as pd

In [3]:
matchmaker = pd.read_csv('/projects/immunestatus/vdjdb/tcrvdb/01_05_2025_TCRvdb.csv', index_col=0)
matchmaker

,name,clonotype_aa,cdr3_alpha_aa,cdr3_beta_aa,TRAV,TRAJ,TRBV,TRBJ,TRBD,TRAV_IMGT,...,hla_short,hla_long,data_origin,vdjdb_score,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,1_5_H3_86_YLQPRTFLL,TRAV12-1_CVVNIDTDKLIF_TRAJ34--TRBV2_CATGGDHNTG...,CVVNIDTDKLIF,CATGGDHNTGELFF,TRAV12-1,TRAJ34,TRBV2,TRBJ2-2,NaN,TRAV12-1*01,...,A2,A*02:01,vdjdb,0.0,198.217526,-2.653196,0.188261,-13.561965,6.730858e-42,1.636410e-40
1,1_6_G24_179_YLQPRTFLL,TRAV5_CAEILDFGNEKLTF_TRAJ48--TRBV20-1_CSARDPSG...,CAEILDFGNEKLTF,CSARDPSGVKLFF,TRAV5,TRAJ48,TRBV20-1,TRBJ1-4,NaN,TRAV5*01,...,A2,A*02:01,vdjdb,1.0,48.227439,-1.112206,0.302166,-3.349832,8.086058e-04,5.774793e-03
2,1_6_H1_84_YLQPRTFLL,TRAV35_CAAMNYGGSQGNLIF_TRAJ42--TRBV6-2_CASSYRG...,CAAMNYGGSQGNLIF,CASSYRGTGLNEQFF,TRAV35,TRAJ42,TRBV6-2,TRBJ2-1,NaN,TRAV35*01,...,A2,A*02:01,vdjdb,0.0,77.593373,0.206727,0.238408,0.447668,6.543928e-01,1.000000e+00
3,1_6_H2_85_YLQPRTFLL,TRAV21_CAVKDTDKLIF_TRAJ34--TRBV7-8_CASSLAGSSYN...,CAVKDTDKLIF,CASSLAGSSYNSPLHF,TRAV21,TRAJ34,TRBV7-8,TRBJ1-6,NaN,TRAV21*01,...,A2,A*02:01,vdjdb,0.0,21.861277,1.116579,0.451138,2.253366,2.423609e-02,1.296120e-01
4,1_6_H3_86_YLQPRTFLL,TRAV12-1_CVVNRNNDMRF_TRAJ43--TRBV2_CATQSDPNTGE...,CVVNRNNDMRF,CATQSDPNTGELFF,TRAV12-1,TRAJ43,TRBV2,TRBJ2-2,NaN,TRAV12-1*01,...,A2,A*02:01,vdjdb,0.0,251.554645,-2.851169,0.172124,-15.983631,1.661776e-57,6.701844e-56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3688,3_20_E7_54_KPVPEVKIL,TRAV14/DV4_CAMRESSNYQLIW_TRAJ33--TRBV2_CASTRGQ...,CAMRESSNYQLIW,CASTRGQRNGAFF,TRAV14/DV4,TRAJ33,TRBV2,TRBJ1-1,NaN,TRAV14_DV4*01,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3689,3_20_E9_56_SLIYSTAAL,TRAV14/DV4_CAMREKPGGYQKVTF_TRAJ13--TRBV19_CASS...,CAMREKPGGYQKVTF,CASSLSRRRSRDDNEQFF,TRAV14/DV4,TRAJ13,TRBV19,TRBJ2-1,NaN,TRAV14_DV4*01,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3690,3_20_E10_57_SPLPSYAAF,TRAV3_CAVRDTTNWGKLQF_TRAJ24--TRBV7-2_CASRSGGGS...,CAVRDTTNWGKLQF,CASRSGGGSYEQYF,TRAV3,TRAJ24,TRBV7-2,TRBJ2-7,NaN,TRAV3*01,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3691,3_19_D8_43_VLLGVKLFGV,TRAV2-1_CAVEGDTGFQKLVF_TRAJ8--TRBV13-1_CASSSPR...,CAVEGDTGFQKLVF,CASSSPRSSRDTDTQYF,TRAV2-1*01,TRAJ8,TRBV13-1*01,TRBJ2-3,NaN,TRAV2*01,...,A2,A*02:01,vdjdb,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3692,3_20_F1_60_KPLPEVKIL,TRAV14/DV4_CAMRLYNFNKFYF_TRAJ21--TRBV3-1_CASSH...,CAMRLYNFNKFYF,CASSHEWGSNTGELFF,TRAV14/DV4,TRAJ21,TRBV3-1,TRBJ2-2,NaN,TRAV14_DV4*01,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
full_db = pd.read_csv('./vdjdb_full_scored.txt', sep='\t')
full_db

/scratch/ipykernel_3435301/539200269.py:1: DtypeWarning: Columns (5,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.
  full_db = pd.read_csv('./vdjdb_full_scored.txt', sep='\t')

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member
0,NaN,NaN,NaN,CASSIVGGNEQFF,TRBV19*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIVGGNEQFF', 'cdr3_old': 'CASSIVG...",3,1
1,NaN,NaN,NaN,CASSMRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSMRSTGELFF', 'cdr3_old': 'CASSMRS...",3,1
2,NaN,NaN,NaN,CASSIRSAWAQYF,TRBV19*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSAWAQYF', 'cdr3_old': 'CASSIRS...",2,0
3,NaN,NaN,NaN,CASSQRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSQRSTGELFF', 'cdr3_old': 'CASSQRS...",2,1
4,NaN,NaN,NaN,CASSIRSSYEQYF,TRBV19*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSSYEQYF', 'cdr3_old': 'CASSIRS...",3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131941,NaN,NaN,NaN,CASSPSARGNQPQHF,TRBV2*01,TRBD1*01,TRBJ1-5*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSPSARGNQPQHF', 'cdr3_old': 'CASSP...",0,0
131942,NaN,NaN,NaN,CASSVGTSGVGEQYF,TRBV2*01,TRBD2*01,TRBJ2-7*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSVGTSGVGEQYF', 'cdr3_old': 'CASSV...",0,0
131943,NaN,NaN,NaN,CASSALASGGDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSALASGGDTQYF', 'cdr3_old': 'CASSA...",0,1
131944,NaN,NaN,NaN,CASSRLAGGMDEQFF,TRBV2*01,TRBD2*02,TRBJ2-1*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRLAGGMDEQFF', 'cdr3_old': 'CASSR...",3,1
131945,NaN,NaN,NaN,CASSRRTSGGTDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRRTSGGTDTQYF', 'cdr3_old': 'CASS...",2,1

In [7]:
full_db = full_db[full_db['cdr3.alpha'].apply(pd.notnull) & full_db['cdr3.beta'].apply(pd.notnull)]
full_db

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,GLC1B4,GLC,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,CLG3A10,CLG,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5D11,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATEGDSGYSTLTF', 'cdr3_old': 'CATEGD...","{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5B5,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,YVL16D1,YVL,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0

In [8]:
full_db

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,GLC1B4,GLC,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,CLG3A10,CLG,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5D11,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATEGDSGYSTLTF', 'cdr3_old': 'CATEGD...","{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5B5,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,YVL16D1,YVL,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0

In [29]:
from Stitchr import stitchrfunctions as fxn
from Stitchr import stitchr as st

from Bio.Seq import Seq

In [21]:
def get_aa_seq_cdr3(v, j, cdr3, chain):
    
    chain = chain
    species = 'HUMAN'

    # initialise the necessary data
    tcr_dat, functionality, partial = fxn.get_ref_data(chain, st.gene_types, species)
    codons = fxn.get_optimal_codons('', species)
    j_res, low_conf_js = fxn.get_j_motifs(species)
    c_res = fxn.get_c_motifs(species)
    
    c = 'TRBC1*01' if chain == 'TRB' else 'TRAC*01'
    # provide details of the rearrangement to be stitched
    tcr_bits = {'v': v, 'j': j, 'cdr3': cdr3,
                'l': v, 'c': c, 'mode': '',
                'skip_c_checks': False, 'skip_n_checks': False, 'no_leader': False,
                'species': species, 'seamless': False,
                '5_prime_seq': '', '3_prime_seq': '', 'name': 'my-cool-TCR'}

    # then run stitchr on that rearrangement
    stitched = st.stitch(tcr_bits, tcr_dat, functionality, partial, codons, 3, '',
                         c_res, j_res, low_conf_js)

    res_aa = str(Seq(stitched['stitched_nt']).translate())
    
    return res_aa

In [22]:
full_db_homosapisens = full_db[full_db.species == 'HomoSapiens']

In [26]:
full_db_homosapisens

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,NaN,NS1(196-206),PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,GLC1B4,GLC,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,CLG3A10,CLG,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5D11,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATEGDSGYSTLTF', 'cdr3_old': 'CATEGD...","{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,FLY5B5,FLY,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,YVL16D1,YVL,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0

In [27]:
clone

cdr3.alpha                                                     CAYRSAFKLTF
v.alpha                                                    TRAV38-2/DV8*01
j.alpha                                                          TRAJ48*01
cdr3.beta                                                  CAWSVPLGRREKLFF
v.beta                                                           TRBV30*01
d.beta                                                                 NaN
j.beta                                                          TRBJ1-4*01
species                                                        HomoSapiens
mhc.a                                                          HLA-A*02:01
mhc.b                                                                  B2M
mhc.class                                                             MHCI
antigen.epitope                                                  YVLDHLIVV
antigen.gene                                                         BRLF1
antigen.species                                                        EBV
reference.id                                                 PMID:35525797
method.identification                                        tetramer-sort
method.frequency                                                      2/26
method.singlecell                                                      yes
method.sequencing                                                 illumina
method.verification                                 antigen-loaded-targets
meta.study.id                                                      YVL16D1
meta.cell.subset                                                      CD8+
meta.subject.cohort                               EBV-seropositive,healthy
meta.subject.id                                                         G6
meta.replica.id                                                        NaN
meta.clone.id                                                      YVL16D1
meta.epitope.id                                                        YVL
meta.tissue                                            stem-cell-graft,TCL
meta.donor.MHC                                                 HLA-A*02:01
meta.donor.MHC.method                                                  NaN
meta.structure.id                                                      NaN
cdr3fix.alpha            {'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...
cdr3fix.beta             {'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...
vdjdb.score                                                              3
cluster.member                                                           0
Name: 131361, dtype: object

In [30]:
get_aa_seq_cdr3(
            clone['v.alpha'],
            clone['j.alpha'],
            clone['cdr3.alpha'],
            'TRA'
                                                    )

'MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYDTSESDYYLFWYKQPPSRQMILVIRQEAYKQQNATENRFSVNFQKAAKSFSLKISDSQLGDAAMYFCAYRSAFKLTFGTGTRLTIIPNIQNPDPAVYQLRDSKSSDKSVCLFTDFDSQTNVSQSKDSDVYITDKTVLDMRSMDFKSNSAVAWSNKSDFACANAFNNSIIPEDTFFPSPESSCDVKLVEKSFETDTNLNFQNLSVIGFRILLLKVAGFNLLMTLRLWSS'

In [31]:
res_dict = {}

for clone_id, clone in full_db_homosapisens.iterrows():
    
    try:
        res_dict[clone_id] = {'TRA_aa_seq': get_aa_seq_cdr3(
            clone['v.alpha'],
            clone['j.alpha'],
            clone['cdr3.alpha'],
            'TRA'
                                                    ),
            'TRB_aa_seq': get_aa_seq_cdr3(
            clone['v.beta'],
            clone['j.beta'],
            clone['cdr3.beta'],
            'TRB')
                             }
    except:
        pass

Note: while a C-terminal CDR3:J germline match has been found, it was only the string "QFF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "F", which occurs in two positions.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LTF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "YF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "QYF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "TF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "AFF".
No valid joining region allele determined yet for TRAJ16.
Defaulting to *01 for the joining region, in the absence of a preferred allele file being specified.
NB: the prototypical '*01' allele is being used for the joining region by default, but other alleles are available - consider double checking the right allele is asked for.
No valid joining region allele determined yet for TRAJ58.
Warning: gene TRAJ58*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
CDR3 provided does not end with the expected residue for this J gene (F). Deletion this far in to the J is extremely unlikely.
No valid leader region allele determined yet for TRAV14-1.
Defaulting to *01 for the leader region, in the absence of a preferred allele file being specified.
NB: the prototypical '*01' allele is being used for the leader region by default, but other alleles are available - consider double checking the right allele is asked for.
Warning: gene TRAV14-1*01 has an assigned functionality of 'P', and thus may not express or function correctly.
No valid variable region allele determined yet for TRAV14-1.
Defaulting to *01 for the variable region, in the absence of a preferred allele file being specified.
NB: the prototypical '*01' allele is being used for the variable region by default, but other alleles are available - consider double checking the right allele is asked for.
Cannot find the sequence of the requested allele, TRAJ16*01       , for the joining sequence in the input FASTA data.
Cannot find the sequence of the requested allele, TRAJ58*01       , for the joining sequence in the input FASTA data.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "F".
No valid joining region allele determined yet for TRAJ35.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "YTF".
No valid leader region allele determined yet for TRBV23-1.
Warning: gene TRBV23-1*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
No valid variable region allele determined yet for TRBV23-1.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "FF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "STF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "MRF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "QHF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "FYF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "RF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "VF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "IIF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "S".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "HF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LFF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LIF".
Cannot find the sequence of the requested allele, TRBV10-3*02, for the leader sequence in the input FASTA data.
No valid leader region allele determined yet for TRBV10-3.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "IW".
No valid leader region allele determined yet for TRBV21-1.
Warning: gene TRBV21-1*01 has an assigned functionality of 'P', and thus may not express or function correctly.
No valid variable region allele determined yet for TRBV21-1.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "IF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "MF".
Cannot find the sequence of the requested allele, TRBV24/OR9-2*01, for the leader sequence in the input FASTA data.
No valid leader region allele determined yet for TRBV24/OR9-2.
No sequence found for TRBV24/OR9-2*01 for the LEADER region. TRBV24/OR9-2*03 is being used instead - please double check either the intended allele or that this is a suitable replacement.
Warning: gene TRBV24/OR9-2*03 has an assigned functionality of 'P', and thus may not express or function correctly.
Warning: gene TRBV24/OR9-2*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
Warning: gene TRBV20/OR9-2*03 has an assigned functionality of 'ORF', and thus may not express or function correctly.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "PTF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "SF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "L".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LSF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "FVF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "IYF".
CDR3 provided does not end with the expected residue for this J gene (C). Deletion this far in to the J is extremely unlikely.
CDR3 provided does not end with the expected residue for this J gene (W). Deletion this far in to the J is extremely unlikely.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LHF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LLF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "TIF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "YIF".
Cannot find the sequence of the requested allele, TRBV20-1*02, for the variable sequence in the input FASTA data.
No valid variable region allele determined yet for TRBV20-1.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "W".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "A".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LMF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LVF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "NF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "VIF".
Warning: gene TRAJ2*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
No valid joining region allele determined yet for TRAJ25.
Warning: gene TRAJ25*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "VTF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LIW".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LNF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "G", which occurs in two positions.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "QF".

In [32]:
motif_input_data = pd.concat([full_db_homosapisens, pd.DataFrame(res_dict).T], axis=1)

motif_input_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member,TRA_aa_seq,TRB_aa_seq
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATEGDSGYSTLTF', 'cdr3_old': 'CATEGD...","{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...

In [35]:
#motif_input_data = pd.read_csv('HS_data_aggregated.tsv', sep='\t', index_col=0)
motif_input_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member,TRA_aa_seq,TRB_aa_seq
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAGSGGSNYKLTF', 'cdr3_old': 'CAY...","{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSATGYALNF', 'cdr3_old': 'CAYRSAT...","{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CALSEYSGGYQKVTF', 'cdr3_old': 'CALSE...","{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAVDNYGQNFVF', 'cdr3_old': 'CAVDNYGQ...","{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,PBMC,"HLA-A*01:01, HLA-A*03:01, HLA-B*07:02, HLA-B*0...",NaN,"Fig 9, Supp Fig 5, Supp Table 5-8","{'cdr3': 'CAYRSAIQDKIIF', 'cdr3_old': 'CAYRSAI...","{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAESTSWGKLQF', 'cdr3_old': 'CAESTSWG...","{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAILMDSNYQLIW', 'cdr3_old': 'CAILMDS...","{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATEGDSGYSTLTF', 'cdr3_old': 'CATEGD...","{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CATVGNSGYSTLTF', 'cdr3_old': 'CATVGN...","{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"stem-cell-graft,TCL",HLA-A*02:01,NaN,NaN,"{'cdr3': 'CAYRSAFKLTF', 'cdr3_old': 'CAYRSAFKL...","{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...

In [42]:
hla_data = pd.read_csv('../hla_table_full.tsv', sep='\t')
hla_data['proteine_type_allele'] = hla_data.allele.apply(lambda x: 'HLA-'+':'.join(x.split(':')[0:2]))
hla_data['allele_subtype'] = hla_data['proteine_type_allele'].apply(lambda x: x.split(':')[0])
hla_dict = hla_data.set_index('proteine_type_allele')['hla_aa_seq'].to_dict()

hla_dict['B2M'] = 'MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWVSSIRH'

motif_input_data['mhc.a.short'] = motif_input_data['mhc.a'].apply(lambda x: ':'.join(x.split(':')[0:2]))

motif_input_data['mhc.b.short'] = motif_input_data['mhc.b'].apply(lambda x: ':'.join(x.split(':')[0:2]) if x != 'B2M' else 'B2M')


motif_input_data['mhc.a.aa.seq'] = motif_input_data['mhc.a.short'].apply(lambda x: hla_dict.get(x))
motif_input_data['mhc.b.aa.seq'] = motif_input_data['mhc.b.short'].apply(lambda x: hla_dict.get(x))

In [ ]:
pd.DataFrame(res_dict).T

Empty DataFrame
Columns: []
Index: []

In [44]:
motif_input_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,cdr3fix.beta,vdjdb.score,cluster.member,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,mhc.b.short,mhc.a.aa.seq,mhc.b.aa.seq
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,"{'cdr3': 'CASSLMTNQPQHF', 'cdr3_old': 'CASSLMT...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,"{'cdr3': 'CASSLYGSVQNEQFF', 'cdr3_old': 'CASSL...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,"{'cdr3': 'CASSVATSGGSQQFF', 'cdr3_old': 'CASSV...",3,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,"{'cdr3': 'CASSLYGADTQYF', 'cdr3_old': 'CASSLYG...",3,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,"{'cdr3': 'CASSPHPGTSGGASYNEQFF', 'cdr3_old': '...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"{'cdr3': 'CSVGTGGTNEKLFF', 'cdr3_old': 'CSVGTG...",2,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,"{'cdr3': 'CASSEDGMNTEAFF', 'cdr3_old': 'CASSED...",3,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,"{'cdr3': 'CASSYQGGNYGYTF', 'cdr3_old': 'CASSYQ...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"{'cdr3': 'CASSKQGGNIQYF', 'cdr3_old': 'CASSKQG...",3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,"{'cdr3': 'CAWSVPLGRREKLFF', 'cdr3_old': 'CAWSV...",3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...

In [45]:
import hashlib

def hash_string(input_string: str) -> str:
    """
    Computes a SHA-256 hash of the input string and returns it as a hexadecimal string.
    
    This provides a consistent, deterministic hash across different Python runs.
    Note: Python's built-in hash() function is not consistent due to hash randomization.
    
    Args:
        input_string (str): The string to hash.
    
    Returns:
        str: The hexadecimal representation of the hash.
    """
    # Encode the string to bytes
    encoded = input_string.encode('utf-8')
    
    # Create a SHA-256 hash object
    sha256_hash = hashlib.sha256()
    
    # Update the hash object with the encoded string
    sha256_hash.update(encoded)
    
    # Get the hexadecimal digest
    return sha256_hash.hexdigest()

# Example usage:
if __name__ == "__main__":
    example = "Hello, world!"
    print(f"Hash of '{example}': {hash_string(example)}")

Hash of 'Hello, world!': 315f5bdb76d078c43b8ac0064e4a0164612b1fce77c869345bfc94c75894edd3

In [46]:
motif_input_data['index_seq'] = motif_input_data['cdr3.alpha'] + motif_input_data['v.alpha'] + motif_input_data['j.alpha'] + motif_input_data['cdr3.beta'] + motif_input_data['v.beta'] + motif_input_data['j.beta'] + motif_input_data['mhc.a'] + motif_input_data['mhc.b'] + motif_input_data['antigen.epitope']

In [54]:
motif_input_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,vdjdb.score,cluster.member,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,mhc.b.short,mhc.a.aa.seq,mhc.b.aa.seq,index_seq
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,3,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,2,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAESTSWGKLQFTRAV5*01TRAJ24*02CSVGTGGTNEKLFFTRB...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,3,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAILMDSNYQLIWTRAV21*01TRAJ33*01CASSEDGMNTEAFFT...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATEGDSGYSTLTFTRAV17*01TRAJ11*01CASSYQGGNYGYTF...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,3,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATVGNSGYSTLTFTRAV17*01TRAJ11*01CASSKQGGNIQYFT...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,3,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAFKLTFTRAV38-2/DV8*01TRAJ48*01CAWSVPLGRRE...

In [55]:
motif_input_data = motif_input_data.dropna(subset = 'index_seq')

In [56]:
motif_input_data['TCR_hash'] = motif_input_data.index_seq.apply(lambda x: hash_string(x))


motif_input_data

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,cluster.member,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,mhc.b.short,mhc.a.aa.seq,mhc.b.aa.seq,index_seq,TCR_hash
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...,20350288084b42c9b68db20e8e8f90466438e3619b6116...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAESTSWGKLQFTRAV5*01TRAJ24*02CSVGTGGTNEKLFFTRB...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAILMDSNYQLIWTRAV21*01TRAJ33*01CASSEDGMNTEAFFT...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATEGDSGYSTLTFTRAV17*01TRAJ11*01CASSYQGGNYGYTF...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATVGNSGYSTLTFTRAV17*01TRAJ11*01CASSKQGGNIQYFT...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAFKLTFTRAV38-2/DV8*01TRAJ48*01CAWSVPLGRRE...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...

In [58]:
'3cd07336647eb7fb5b474f32a21e4e163b09cab00fc69b1345b09500556203d6' in set(motif_input_data.TCR_hash)

True

In [59]:
motif_input_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,cluster.member,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,mhc.b.short,mhc.a.aa.seq,mhc.b.aa.seq,index_seq,TCR_hash
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...,20350288084b42c9b68db20e8e8f90466438e3619b6116...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-B*07:02,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,B2M,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,1,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAESTSWGKLQFTRAV5*01TRAJ24*02CSVGTGGTNEKLFFTRB...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAILMDSNYQLIWTRAV21*01TRAJ33*01CASSEDGMNTEAFFT...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATEGDSGYSTLTFTRAV17*01TRAJ11*01CASSYQGGNYGYTF...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,NaN,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,...,1,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CATVGNSGYSTLTFTRAV17*01TRAJ11*01CASSKQGGNIQYFT...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,NaN,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,...,0,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,B2M,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,CAYRSAFKLTFTRAV38-2/DV8*01TRAJ48*01CAWSVPLGRRE...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...

In [62]:
structures_vdjdb = pd.read_csv('/projects/structures/Models_VDJdb/VDJdb_Models_annotation_w_new_names.csv')

structures_vdjdb

,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id
0,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
1,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
2,VDJdb_Model_10_min.pdb,CAEPGSQGNLIF,CASSSRSSYEQYF,False,True,VDJdb_Model_134_min.pdb,90 G->E,1oga_TRA_CAEPGSQGNLIF_TRB_CASSSRSSYEQYF_from1_...
3,VDJdb_Model_10_repacked.pdb,CAEPGSQGNLIF,CASSSRSSYEQYF,False,True,VDJdb_Model_134_min.pdb,90 G->E,1oga_TRA_CAEPGSQGNLIF_TRB_CASSSRSSYEQYF_from1_...
4,VDJdb_Model_100_min.pdb,CAGAGSQGNLIF,CASSTRSSYEQYF,True,False,1oga_al2_al2_cleaned.pdb,93 S->T,1oga_TRA_CAGAGSQGNLIF_TRB_CASSTRSSYEQYF_order1...
...,...,...,...,...,...,...,...,...
3208,VDJdb_Model_997_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSFEAFF,True,False,VDJdb_Model_1025_min.pdb,97 Y->F,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSFEAFF_fro...
3209,VDJdb_Model_998_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...
3210,VDJdb_Model_998_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...
3211,VDJdb_Model_999_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...
3212,VDJdb_Model_999_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...

In [75]:
len(set(structures_vdjdb['pdb.id'].apply(lambda x: x.split('_')[0])))

32

In [76]:
len(set(full_db['meta.structure.id'].str.lower()).intersection(set(structures_vdjdb['pdb.id'].apply(lambda x: x.split('_')[0]))))

29

In [82]:
set(structures_vdjdb['pdb.id'].apply(lambda x: x.split('_')[0])).difference(set(full_db['meta.structure.id'].str.lower()))

{'2vlk', '3mv8', '3mv9'}

In [84]:
structure_chunk = pd.read_csv('./PDB_Database.txt', sep='\t')
structure_chunk

,chunk.id,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,...,meta.subset.frequency,meta.subject.cohort,meta.subject.id,meta.replica.id,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id
0,1,CAVTTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1ao7
1,2,CAAMEGAQKLVF,TRAV29/DV5*01,TRAJ54*01,CASSYPGGGFYEQYF,TRBV6-5*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1bd2
2,3,CAATGSFNKLTF,TRAV14D-2*01,TRAJ4*01,CASGGQGRAEQFF,TRBV13-2*01,NaN,TRBJ2-1*01,MusMusculus,H-2Aa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1d9k
3,4,CAMRGDYGGSGNKLIF,TRAV16*01,TRAJ32*01,CTCSADRVGNTLYF,TRBV1*01,NaN,TRBJ1-3*01,MusMusculus,H-2Kb,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1fo0
4,5,CAVSESPFGNEKLTF,TRAV8-4*01,TRAJ48*01,CASSSTGLPYGYTF,TRBV28*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-DRA*01:02:03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1fyt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,303,CLVGDMDQAGTALI,TRAV4*01,NaN,CASSLGEGRVDGYTF,TRBV5-6*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-C*08:02,...,NaN,NaN,4095,NaN,NaN,KRASG12D,TIL,NaN,NaN,6ULI
303,304,CAAAMDSSYKLIF,TRAV12-2*01,NaN,CASSDPGTEAFF,TRBV10-2*01,NaN,TRBJ1-1*01,HomoSapiens,HLA-C*08:02,...,NaN,NaN,4095,NaN,NaN,KRASG12D,TIL,NaN,NaN,6ULR
304,305,CLVGDRDQAGTALIF,TRAV4*01,TRAJ15*01,CASSFGQSSTYGYTF,TRBV5-6*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-C*08:02,...,NaN,NaN,4095,NaN,NaN,KRASG12D,TIL,NaN,NaN,6ULN
305,306,CLVGDMDQAGTALIF,TRAV4*01,TRAJ15*01,CASSLGRASNQPQHF,TRBV5-6*01,NaN,TRBJ1-5*01,HomoSapiens,HLA-C*08:02,...,NaN,NaN,4095,NaN,NaN,KRASG12D,TIL,NaN,NaN,6ULK
306,307,CLVGDMDQAGTALIF,TRAV4*01,TRAJ15*01,CASSLGQTNYGYTF,TRBV5-6*01,NaN,TRBJ1-2*01,HomoSapiens,HLA-C*08:02,...,NaN,NaN,3955,NaN,NaN,KRASG12D,TIL,NaN,NaN,6UON

In [85]:
structure_chunk[structure_chunk['meta.structure.id'] == '2vlk']

,chunk.id,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,...,meta.subset.frequency,meta.subject.cohort,meta.subject.id,meta.replica.id,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id
34,35,CAGAGSQGNLIF,TRAV27*01,TRAJ42*01,CASSSRSSYEQYF,TRBV19*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:48,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2vlk

In [88]:
structure_chunk['meta.structure.id'].str.lower()

0      1ao7
1      1bd2
2      1d9k
3      1fo0
4      1fyt
       ...
302    6uli
303    6ulr
304    6uln
305    6ulk
306    6uon
Name: meta.structure.id, Length: 307, dtype: object

In [89]:
set(structures_vdjdb['pdb.id'].apply(lambda x: x.split('_')[0])).difference(set(structure_chunk['meta.structure.id'].str.lower()))

set()

In [92]:
structures_vdjdb['structure_id'] = structures_vdjdb['pdb.id'].apply(lambda x: x.split('_')[0])

structures_vdjdb

,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id,structure_id
0,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,1ao7
1,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,1ao7
2,VDJdb_Model_10_min.pdb,CAEPGSQGNLIF,CASSSRSSYEQYF,False,True,VDJdb_Model_134_min.pdb,90 G->E,1oga_TRA_CAEPGSQGNLIF_TRB_CASSSRSSYEQYF_from1_...,1oga
3,VDJdb_Model_10_repacked.pdb,CAEPGSQGNLIF,CASSSRSSYEQYF,False,True,VDJdb_Model_134_min.pdb,90 G->E,1oga_TRA_CAEPGSQGNLIF_TRB_CASSSRSSYEQYF_from1_...,1oga
4,VDJdb_Model_100_min.pdb,CAGAGSQGNLIF,CASSTRSSYEQYF,True,False,1oga_al2_al2_cleaned.pdb,93 S->T,1oga_TRA_CAGAGSQGNLIF_TRB_CASSTRSSYEQYF_order1...,1oga
...,...,...,...,...,...,...,...,...,...
3208,VDJdb_Model_997_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSFEAFF,True,False,VDJdb_Model_1025_min.pdb,97 Y->F,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSFEAFF_fro...,5euo
3209,VDJdb_Model_998_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...,5euo
3210,VDJdb_Model_998_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...,5euo
3211,VDJdb_Model_999_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...,5euo
3212,VDJdb_Model_999_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...,5euo

In [93]:
structure_chunk['meta.structure.id'] = structure_chunk['meta.structure.id'].str.lower()

In [94]:
structure_chunk.rename(columns = {'meta.structure.id': 'structure_id'}, inplace=True)

In [ ]:
structures_vdjdb.rename(columns = {''})

In [107]:
structure_chunk = structure_chunk[['v.alpha', 'j.alpha', 'v.beta', 'j.beta', 'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'structure_id']].drop_duplicates()

In [109]:
merged_df = pd.merge(structure_chunk, structures_vdjdb, on='structure_id', how='inner')
merged_df

,v.alpha,j.alpha,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,structure_id,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id
0,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
1,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
2,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_min.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...
3,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_repacked.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...
4,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_3_min.pdb,CILPLAGGTSYGKLTF,CASSSGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->S,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSSGQAYEQYF_or...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4100,TRAV27*01,TRAJ37*01,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02,B2M,GILGFVFTL,5euo,VDJdb_Model_997_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSFEAFF,True,False,VDJdb_Model_1025_min.pdb,97 Y->F,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSFEAFF_fro...
4101,TRAV27*01,TRAJ37*01,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02,B2M,GILGFVFTL,5euo,VDJdb_Model_998_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...
4102,TRAV27*01,TRAJ37*01,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02,B2M,GILGFVFTL,5euo,VDJdb_Model_998_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGELFF,True,False,VDJdb_Model_1004_min.pdb,99 Q->L,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGELFF_fro...
4103,TRAV27*01,TRAJ37*01,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02,B2M,GILGFVFTL,5euo,VDJdb_Model_999_min.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...
4104,TRAV27*01,TRAJ37*01,TRBV19*01,TRBJ2-7*01,HomoSapiens,HLA-A*02,B2M,GILGFVFTL,5euo,VDJdb_Model_999_repacked.pdb,CAGAIGPSNTGKLIF,CASSIRSSGEQFF,True,False,VDJdb_Model_991_min.pdb,97 D->G,5euo_TRA_CAGAIGPSNTGKLIF_TRB_CASSIRSSGEQFF_fro...

In [117]:
merged_df['vdjdb.pdb.id'].dropna().drop_duplicates()

0               VDJdb_Model_1_min.pdb
1          VDJdb_Model_1_repacked.pdb
2               VDJdb_Model_2_min.pdb
3          VDJdb_Model_2_repacked.pdb
4               VDJdb_Model_3_min.pdb
                    ...
3208    VDJdb_Model_1604_repacked.pdb
3209         VDJdb_Model_1605_min.pdb
3210    VDJdb_Model_1605_repacked.pdb
3211         VDJdb_Model_1606_min.pdb
3212    VDJdb_Model_1606_repacked.pdb
Name: vdjdb.pdb.id, Length: 3211, dtype: object

In [121]:
merged_df = merged_df.drop_duplicates('vdjdb.pdb.id')

In [122]:
merged_df

,v.alpha,j.alpha,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,structure_id,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id
0,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
1,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...
2,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_min.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...
3,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_repacked.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...
4,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_3_min.pdb,CILPLAGGTSYGKLTF,CASSSGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->S,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSSGQAYEQYF_or...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1604_repacked.pdb,CAVNRYDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,467 D->Y,7rtr_TRA_CAVNRYDKIIF_TRB_CASSPDIEQYF_order1_re...
3209,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_min.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...
3210,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_repacked.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...
3211,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_min.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_mi...
3212,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_repacked.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_re...

In [123]:
res_dict = {}

for clone_id, clone in merged_df.iterrows():
    
    try:
        res_dict[clone_id] = {'TRA_aa_seq': get_aa_seq_cdr3(
            clone['v.alpha'],
            clone['j.alpha'],
            clone['cdr3.alpha'],
            'TRA'
                                                    ),
            'TRB_aa_seq': get_aa_seq_cdr3(
            clone['v.beta'],
            clone['j.beta'],
            clone['cdr3.beta'],
            'TRB')
                             }
    except:
        pass

Note: while a C-terminal CDR3:J germline match has been found, it was only the string "F", which occurs in two positions.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "YF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "F".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "QYF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "IF".
Warning: gene TRAJ58*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "MF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "YTF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "TF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LMF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LFF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "RF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "MRF".
Note: while a C-terminal CDR3:J germline match has been found, it was only the string "LIF".
Warning: gene TRAV14-1*01 has an assigned functionality of 'P', and thus may not express or function correctly.
Warning: gene TRBV17*01 has an assigned functionality of 'ORF', and thus may not express or function correctly.

In [125]:
additional_structures_input = pd.concat([merged_df, pd.DataFrame(res_dict).T], axis=1)

additional_structures_input

,v.alpha,j.alpha,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,structure_id,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id,TRA_aa_seq,TRB_aa_seq
0,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
1,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
2,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_min.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
3,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_repacked.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
4,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_3_min.pdb,CILPLAGGTSYGKLTF,CASSSGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->S,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSSGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1604_repacked.pdb,CAVNRYDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,467 D->Y,7rtr_TRA_CAVNRYDKIIF_TRB_CASSPDIEQYF_order1_re...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3209,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_min.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3210,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_repacked.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3211,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_min.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_mi...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3212,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_repacked.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_re...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...

In [126]:
additional_structures_input

,v.alpha,j.alpha,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,structure_id,vdjdb.pdb.id,cdr3.alpha,cdr3.beta,orig.alpha,orig.beta,vdjdb.pdb.id.from,mutation.signature,pdb.id,TRA_aa_seq,TRB_aa_seq
0,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_min.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
1,TRAV12-2*01,TRAJ24*01,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,1ao7,VDJdb_Model_1_repacked.pdb,CAVKTDSWGKLQF,CASRPGLAGGRPEQYF,False,True,1ao7_al2_al2_cleaned.pdb,91 T->K,1ao7_TRA_CAVKTDSWGKLQF_TRB_CASRPGLAGGRPEQYF_or...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...
2,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_min.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
3,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_2_repacked.pdb,CILPLAGGTSYGKLTF,CASSIGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->I,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSIGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
4,TRAV26-2*01,TRAJ52*01,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,1mi5,VDJdb_Model_3_min.pdb,CILPLAGGTSYGKLTF,CASSSGQAYEQYF,True,False,1mi5_al2_al2_cleaned.pdb,94 L->S,1mi5_TRA_CILPLAGGTSYGKLTF_TRB_CASSSGQAYEQYF_or...,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1604_repacked.pdb,CAVNRYDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,467 D->Y,7rtr_TRA_CAVNRYDKIIF_TRB_CASSPDIEQYF_order1_re...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3209,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_min.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3210,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1605_repacked.pdb,CAVNSGDKIIF,CASSPDIEQYF,False,True,VDJdb_Model_1602_min.pdb,466 R->S,7rtr_TRA_CAVNSGDKIIF_TRB_CASSPDIEQYF_from1_TRA...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3211,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_min.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_mi...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...
3212,TRAV12-2*01,TRAJ30*01,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,7rtr,VDJdb_Model_1606_repacked.pdb,CAVNVDDKIIF,CASSPDIEQYF,False,True,7rtr_al2_al2_cleaned.pdb,466 R->V,7rtr_TRA_CAVNVDDKIIF_TRB_CASSPDIEQYF_order1_re...,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...

In [127]:
hla_data = pd.read_csv('../hla_table_full.tsv', sep='\t')
hla_data['proteine_type_allele'] = hla_data.allele.apply(lambda x: 'HLA-'+':'.join(x.split(':')[0:2]))
hla_data['allele_subtype'] = hla_data['proteine_type_allele'].apply(lambda x: x.split(':')[0])
hla_dict = hla_data.set_index('proteine_type_allele')['hla_aa_seq'].to_dict()

hla_dict['B2M'] = 'MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWVSSIRH'

additional_structures_input['mhc.a.short'] = additional_structures_input['mhc.a'].apply(lambda x: ':'.join(x.split(':')[0:2]))

additional_structures_input['mhc.b.short'] = additional_structures_input['mhc.b'].apply(lambda x: ':'.join(x.split(':')[0:2]) if x != 'B2M' else 'B2M')


additional_structures_input['mhc.a.aa.seq'] = additional_structures_input['mhc.a.short'].apply(lambda x: hla_dict.get(x))
additional_structures_input['mhc.b.aa.seq'] = additional_structures_input['mhc.b.short'].apply(lambda x: hla_dict.get(x))

In [132]:
additional_structures_input = additional_structures_input[['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta', 'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq', 'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq', 'vdjdb.pdb.id']]

additional_structures_input

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,vdjdb.pdb.id
0,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_min.pdb
1,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_repacked.pdb
2,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_min.pdb
3,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_repacked.pdb
4,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSSGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_3_min.pdb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb

In [134]:
additional_structures_input.rename(columns= {'vdjdb.pdb.id': 'pdb_file'}, inplace=True)

additional_structures_input

A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file
0,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_min.pdb
1,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_repacked.pdb
2,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_min.pdb
3,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_repacked.pdb
4,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSSGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_3_min.pdb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb

In [135]:
additional_structures_input

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file
0,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_min.pdb
1,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_repacked.pdb
2,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_min.pdb
3,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_repacked.pdb
4,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSSGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_3_min.pdb
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb

In [142]:
motif_input_data_to_concat =motif_input_data[['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta', 'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq', 'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq','TCR_hash', 'meta.structure.id']]

motif_input_data_to_concat

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8"
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8"
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8"
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8"
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN

In [159]:
motif_input_data_to_concat.to_csv('data_to_send_table_precursor.tsv', sep='\t')

In [149]:
import os

In [151]:
len(set(motif_input_data_to_concat.TCR_hash.apply(lambda x: 'aligned_' + x + '.pdb')).intersection(set(os.listdir('/projects/structures/clusters/data_to_send/'))))

297

In [153]:
my_files_set = set(os.listdir('/projects/structures/clusters/data_to_send/'))

In [155]:
import numpy as np

In [158]:
motif_input_data_to_concat['pdb_file'] = motif_input_data_to_concat.TCR_hash.apply(lambda x: 'aligned_' + x + '.pdb' if 'aligned_' + x + '.pdb' in my_files_set else np.nan)

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [161]:
motif_input_data_to_concat.pdb_file.dropna()

1159      aligned_e65469dacd705ce72895eba2a2429496b764a2...
1162      aligned_93964a9d39918fff3b481e2e2c49e521ae6481...
1220      aligned_adb892c1da0bd50b6539fb0e50c763748fa957...
1237      aligned_4aa699d22372356b717176ff38e6ac95e12d77...
1243      aligned_fe71db0074bc2e858c5a304d6b508745d089fd...
                                ...
116182    aligned_fd7f839d54ef9a6a2877cecc8ed42b2fe73152...
118039    aligned_7fe34751b3e5da1dc590d9586d987b6d8f0aee...
120826    aligned_0db2fce6f58244194868dfff1af1a281da1bbf...
125021    aligned_3fab22528c71e3b1dbae4f7f54d52d14f098b8...
131356    aligned_0a2f58c3a331352b4a45ff40042dc99c2aa12b...
Name: pdb_file, Length: 610, dtype: object

In [162]:
motif_input_data_to_concat

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN,NaN
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN

In [163]:
motif_input_data_to_concat['structure_type'] = motif_input_data_to_concat.pdb_file.apply(lambda x: 'TCRmodel2' if pd.notnull(x) else 'unmodeled')

motif_input_data_to_concat

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN,unmodeled
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN,unmodeled
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN,NaN,unmodeled
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN,unmodeled
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN,unmodeled

In [164]:
additional_structures_input['structure_type'] = 'scherbinin'

additional_structures_input

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file,structure_type
0,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_min.pdb,scherbinin
1,CAVKTDSWGKLQF,TRAV12-2*01,TRAJ24*01,CASRPGLAGGRPEQYF,TRBV6-5*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01:59,B2M,LLFGYPVYV,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1_repacked.pdb,scherbinin
2,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_min.pdb,scherbinin
3,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSIGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_2_repacked.pdb,scherbinin
4,CILPLAGGTSYGKLTF,TRAV26-2*01,TRAJ52*01,CASSSGQAYEQYF,TRBV7-8*01,TRBJ2-7*01,HomoSapiens,HLA-B*08:01:29,B2M,FLRGRAYGL,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MGTRLLCWVVLGFLGTDHTGAGVSQSPRYKVAKRGQDVALRCDPIS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_3_min.pdb,scherbinin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb,scherbinin
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb,scherbinin
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb,scherbinin
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb,scherbinin
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb,scherbinin

In [165]:
additional_structures_input['confidence'] = 'unknown'

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [166]:
matchmaker = pd.read_csv('/projects/immunestatus/vdjdb/tcrvdb/01_05_2025_TCRvdb.csv')

matchmaker

,Unnamed: 0,name,clonotype_aa,cdr3_alpha_aa,cdr3_beta_aa,TRAV,TRAJ,TRBV,TRBJ,TRBD,...,hla_short,hla_long,data_origin,vdjdb_score,baseMean,log2FoldChange,lfcSE,stat,pvalue,padj
0,0,1_5_H3_86_YLQPRTFLL,TRAV12-1_CVVNIDTDKLIF_TRAJ34--TRBV2_CATGGDHNTG...,CVVNIDTDKLIF,CATGGDHNTGELFF,TRAV12-1,TRAJ34,TRBV2,TRBJ2-2,NaN,...,A2,A*02:01,vdjdb,0.0,198.217526,-2.653196,0.188261,-13.561965,6.730858e-42,1.636410e-40
1,1,1_6_G24_179_YLQPRTFLL,TRAV5_CAEILDFGNEKLTF_TRAJ48--TRBV20-1_CSARDPSG...,CAEILDFGNEKLTF,CSARDPSGVKLFF,TRAV5,TRAJ48,TRBV20-1,TRBJ1-4,NaN,...,A2,A*02:01,vdjdb,1.0,48.227439,-1.112206,0.302166,-3.349832,8.086058e-04,5.774793e-03
2,2,1_6_H1_84_YLQPRTFLL,TRAV35_CAAMNYGGSQGNLIF_TRAJ42--TRBV6-2_CASSYRG...,CAAMNYGGSQGNLIF,CASSYRGTGLNEQFF,TRAV35,TRAJ42,TRBV6-2,TRBJ2-1,NaN,...,A2,A*02:01,vdjdb,0.0,77.593373,0.206727,0.238408,0.447668,6.543928e-01,1.000000e+00
3,3,1_6_H2_85_YLQPRTFLL,TRAV21_CAVKDTDKLIF_TRAJ34--TRBV7-8_CASSLAGSSYN...,CAVKDTDKLIF,CASSLAGSSYNSPLHF,TRAV21,TRAJ34,TRBV7-8,TRBJ1-6,NaN,...,A2,A*02:01,vdjdb,0.0,21.861277,1.116579,0.451138,2.253366,2.423609e-02,1.296120e-01
4,4,1_6_H3_86_YLQPRTFLL,TRAV12-1_CVVNRNNDMRF_TRAJ43--TRBV2_CATQSDPNTGE...,CVVNRNNDMRF,CATQSDPNTGELFF,TRAV12-1,TRAJ43,TRBV2,TRBJ2-2,NaN,...,A2,A*02:01,vdjdb,0.0,251.554645,-2.851169,0.172124,-15.983631,1.661776e-57,6.701844e-56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3688,3688,3_20_E7_54_KPVPEVKIL,TRAV14/DV4_CAMRESSNYQLIW_TRAJ33--TRBV2_CASTRGQ...,CAMRESSNYQLIW,CASTRGQRNGAFF,TRAV14/DV4,TRAJ33,TRBV2,TRBJ1-1,NaN,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3689,3689,3_20_E9_56_SLIYSTAAL,TRAV14/DV4_CAMREKPGGYQKVTF_TRAJ13--TRBV19_CASS...,CAMREKPGGYQKVTF,CASSLSRRRSRDDNEQFF,TRAV14/DV4,TRAJ13,TRBV19,TRBJ2-1,NaN,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3690,3690,3_20_E10_57_SPLPSYAAF,TRAV3_CAVRDTTNWGKLQF_TRAJ24--TRBV7-2_CASRSGGGS...,CAVRDTTNWGKLQF,CASRSGGGSYEQYF,TRAV3,TRAJ24,TRBV7-2,TRBJ2-7,NaN,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN
3691,3691,3_19_D8_43_VLLGVKLFGV,TRAV2-1_CAVEGDTGFQKLVF_TRAJ8--TRBV13-1_CASSSPR...,CAVEGDTGFQKLVF,CASSSPRSSRDTDTQYF,TRAV2-1*01,TRAJ8,TRBV13-1*01,TRBJ2-3,NaN,...,A2,A*02:01,vdjdb,2.0,NaN,NaN,NaN,NaN,NaN,NaN
3692,3692,3_20_F1_60_KPLPEVKIL,TRAV14/DV4_CAMRLYNFNKFYF_TRAJ21--TRBV3-1_CASSH...,CAMRLYNFNKFYF,CASSHEWGSNTGELFF,TRAV14/DV4,TRAJ21,TRBV3-1,TRBJ2-2,NaN,...,B7,B*07:02,vdjdb,0.0,NaN,NaN,NaN,NaN,NaN,NaN

In [168]:
matchmaker.columns

Index(['Unnamed: 0', 'name', 'clonotype_aa', 'cdr3_alpha_aa', 'cdr3_beta_aa',
       'TRAV', 'TRAJ', 'TRBV', 'TRBJ', 'TRBD', 'TRAV_IMGT', 'TRAJ_IMGT',
       'TRBV_IMGT', 'TRBD_IMGT', 'TRBJ_IMGT', 'epitope_aa', 'hla_short',
       'hla_long', 'data_origin', 'vdjdb_score', 'baseMean', 'log2FoldChange',
       'lfcSE', 'stat', 'pvalue', 'padj'],
      dtype='object')

In [176]:
vaidated = matchmaker[matchmaker.padj <= 1e-05]
non_vaidated = matchmaker[matchmaker.padj > 1e-05]

In [188]:
vaidated['index_data'] = vaidated['cdr3_alpha_aa'] + '_' + vaidated['cdr3_beta_aa']  

non_vaidated['index_data'] = non_vaidated['cdr3_alpha_aa'] + '_' + non_vaidated['cdr3_beta_aa']

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [183]:
vaidated.columns

Index(['Unnamed: 0', 'name', 'clonotype_aa', 'cdr3_alpha_aa', 'cdr3_beta_aa',
       'TRAV', 'TRAJ', 'TRBV', 'TRBJ', 'TRBD', 'TRAV_IMGT', 'TRAJ_IMGT',
       'TRBV_IMGT', 'TRBD_IMGT', 'TRBJ_IMGT', 'epitope_aa', 'hla_short',
       'hla_long', 'data_origin', 'vdjdb_score', 'baseMean', 'log2FoldChange',
       'lfcSE', 'stat', 'pvalue', 'padj'],
      dtype='object')

In [191]:
motif_input_data_to_concat['confidence'] = (motif_input_data_to_concat['cdr3.alpha'] + '_' + motif_input_data_to_concat['cdr3.beta']).apply(lambda x: 'validated' if x in set(vaidated.index_data) else 'false' if x in set(non_vaidated.index_data) else 'unknown')
motif_input_data_to_concat


#(motif_input_data_to_concat['cdr3.alpha'] + '_' + motif_input_data_to_concat['cdr3.beta']).apply(lambda x: x in set(vaidated.index_data))

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,unknown
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,unknown
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,unknown
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,unknown
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,unknown
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN,unmodeled,validated
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN,unmodeled,unknown
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN,NaN,unmodeled,unknown
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN,unmodeled,unknown
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN,unmodeled,unknown

In [196]:
motif_input_data_to_concat['confidence'] = motif_input_data_to_concat.T.apply(lambda x: 'validated' if pd.notnull(x['meta.structure.id']) else x['confidence'])

motif_input_data_to_concat

A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN,unmodeled,validated
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN,unmodeled,unknown
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN,NaN,unmodeled,unknown
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN,unmodeled,unknown
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN,unmodeled,unknown

In [201]:
pd.concat([motif_input_data_to_concat, additional_structures_input]).to_csv('./structures_metadata.tsv', sep='\t')

In [202]:
motif_input_data_to_concat

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,GLCTLVAML,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,NaN,NaN,unmodeled,validated
131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,HomoSapiens,HLA-A*02:01,B2M,CLGGLLTMV,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,NaN,NaN,unmodeled,unknown
131359,CATEGDSGYSTLTF,TRAV17*01,TRAJ11*01,CASSYQGGNYGYTF,TRBV6-5*01,TRBJ1-2*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,244824e1e6d18a9d2d21813efdc12c34a672e4974ef8c1...,NaN,NaN,unmodeled,unknown
131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,HomoSapiens,HLA-A*02:01,B2M,FLYALALLL,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,NaN,NaN,unmodeled,unknown
131361,CAYRSAFKLTF,TRAV38-2/DV8*01,TRAJ48*01,CAWSVPLGRREKLFF,TRBV30*01,TRBJ1-4*01,HomoSapiens,HLA-A*02:01,B2M,YVLDHLIVV,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,50c41643ca15960f57f126b24ed2ff5b525612cfad1bec...,NaN,NaN,unmodeled,unknown

In [203]:
whole_data = pd.concat([motif_input_data_to_concat, additional_structures_input])
whole_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_min.pdb,scherbinin,unknown
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_min.pdb,scherbinin,unknown
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown

In [204]:
whole_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_min.pdb,scherbinin,unknown
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_min.pdb,scherbinin,unknown
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown

In [205]:
import urllib.request

def download_pdb(pdb_id, filename=None):
    """
    Download a PDB file from the RCSB Protein Data Bank by its ID.
    
    Args:
    pdb_id (str): The PDB ID (e.g., '1FAT').
    filename (str, optional): The name of the file to save. Defaults to '{pdb_id}.pdb'.
    """
    pdb_id = pdb_id.upper()
    url = f"https://files.rcsb.org/download/{pdb_id}.pdb"
    
    if filename is None:
        filename = f"{pdb_id}.pdb"
    
    try:
        urllib.request.urlretrieve(url, filename)
        print(f"Successfully downloaded {filename}")
    except Exception as e:
        print(f"Error downloading PDB file: {e}")

In [208]:
whole_data['meta.structure.id'].dropna()

993       Fig 9, Supp Fig 5, Supp Table 5-8
994       Fig 9, Supp Fig 5, Supp Table 5-8
995       Fig 9, Supp Fig 5, Supp Table 5-8
996       Fig 9, Supp Fig 5, Supp Table 5-8
1001      Fig 9, Supp Fig 5, Supp Table 5-8
                        ...
130414                                 6VRN
130415                                 6VQO
130418                                 6ULN
130419                                 6ULK
130420                                 6UON
Name: meta.structure.id, Length: 1666, dtype: object

In [213]:
download_pdb('6ulk', '/projects/structures/clusters/data_to_send/6ULK.pdb')

Successfully downloaded /projects/structures/clusters/data_to_send/6ULK.pdb

In [216]:
whole_data.pdb_file.apply(lambda x: download_pdb(x, f'/projects/structures/clusters/data_to_send/{x.upper()}.pdb') if isinstance(x, str) else np.nan)

Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found

KeyboardInterrupt:

In [221]:
whole_data['meta.structure.id'].dropna().drop_duplicates().apply(lambda x: download_pdb(x, f'/projects/structures/clusters/data_to_send/{x.upper()}.pdb'))

Error downloading PDB file: URL can't contain control characters. '/download/FIG 9, SUPP FIG 5, SUPP TABLE 5-8.pdb' (found at least ' ')
Successfully downloaded /projects/structures/clusters/data_to_send/6AVF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6AVG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5EU6.pdb
Error downloading PDB file: URL can't contain control characters. '/download/FIG.2, FIG. 3, FIG.4, FIG. S3, FIG. S4, FIG. S5, FIG. S6, FIG. S7, FIG. S8, FIG. S9, FIG. S10, FIG. S11, FIG. S12, FIG. S13, DATASET S1, DATASET S2, DATASET S3.pdb' (found at least ' ')
Successfully downloaded /projects/structures/clusters/data_to_send/5WKF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5WKH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6MT3.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8RNH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8ROP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8RNG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8VCX.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8VCY.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8VD0.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8VD2.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XCP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5EUO.pdb
Error downloading PDB file: HTTP Error 404: Not Found
Successfully downloaded /projects/structures/clusters/data_to_send/1AO7.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1BD2.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1FYT.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1J8H.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1MI5.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1OGA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1QRN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1QSE.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1QSF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1ZGL.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2AK4.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2BNQ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2BNR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2ESV.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2F53.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2F54.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2GJ6.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2IAM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2IAN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2NX5.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2P5E.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2VLJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2VLR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2XN9.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2YPL.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3D39.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3DXA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3FFC.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3GSN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3H9S.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3HG1.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3KPR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3KPS.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3KXF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3MV7.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3O4L.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3PWP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3QDG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3QDJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3QDM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3QEQ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3QFJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3SJV.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3UTS.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3VXM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3VXR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3VXS.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4C56.pdb
Error downloading PDB file: HTTP Error 404: Not Found
Successfully downloaded /projects/structures/clusters/data_to_send/4EUP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4FTV.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4G8G.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4G9F.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4GG6.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4JFD.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4JFE.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4JFF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4JRX.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4JRY.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4L3E.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4MJI.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4MNQ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4OZF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4OZG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4OZH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4OZI.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4PRH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4PRI.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4PRP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4QOK.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4QRP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4Y19.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4Y1A.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4Z7U.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4Z7V.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4Z7W.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5D2L.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5D2N.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/1YMM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/2WBJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3D3V.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3NFJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3O6F.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3PL6.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/3T0E.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4EUQ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4GRL.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4H1L.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4MAY.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4P4K.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4QRR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4WUU.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/4ZEZ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5BRZ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5BS0.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C07.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C08.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C09.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C0A.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C0B.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5C0C.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5E6I.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5E9D.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5EU6.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5EUO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5HHM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5HHO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5HYJ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5ISZ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5JHD.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5JZI.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5KS9.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5KSA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5KSB.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5MEN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5NHT.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5NME.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5NMF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5NMG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5NQK.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5TEZ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5W1V.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5W1W.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5WKF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5WKH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5XOT.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5XOV.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5YXN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/5YXU.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6AM5.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6AMU.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6AVF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6AVG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6BJ2.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6BJ3.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6BJ8.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6CQL.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6CQN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6CQQ.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6CQR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6D78.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6DFX.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6DKP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6DXF.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6EQA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6EQB.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6MTM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6P64.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6PX6.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6PY2.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6Q3S.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6R2L.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6RP9.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6RPA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6RPB.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6RSY.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6TMO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6TRO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6U3N.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6U3O.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6UON.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VM7.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VM8.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VMA.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VMC.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VMX.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VQO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VRM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VRN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N1E.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N1F.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N6E.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XC9.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XCO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XCP.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6ZKW.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6ZKX.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6ZKY.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7DZM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7DZN.pdb
Error downloading PDB file: HTTP Error 404: Not Found
Error downloading PDB file: HTTP Error 404: Not Found
Successfully downloaded /projects/structures/clusters/data_to_send/7RM4.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7RTR.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7L1D.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7SG0.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7SG1.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7SG2.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7RRG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2S.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2N.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2O.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2R.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2P.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7N2Q.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8CX4.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XCO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6XC9.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8V51.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8V50.pdb
Error downloading PDB file: HTTP Error 404: Not Found
Successfully downloaded /projects/structures/clusters/data_to_send/8EN8.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8ENH.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/8EO8.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7NMG.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/7NME.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VRM.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VRN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6VQO.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6ULN.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6ULK.pdb
Successfully downloaded /projects/structures/clusters/data_to_send/6UON.pdb

993      None
6986     None
6988     None
7076     None
8611     None
         ...
34472    None
34473    None
34476    None
34477    None
34478    None
Name: meta.structure.id, Length: 230, dtype: object

In [230]:
files_set = set(os.listdir('/projects/structures/clusters/data_to_send/'))

existing_structure = whole_data.T.apply(lambda x: str(x['meta.structure.id']).upper() + '.pdb' in files_set)

existing_structure

993     False
994     False
995     False
996     False
1001    False
        ...
3208    False
3209    False
3210    False
3211    False
3212    False
Length: 83402, dtype: bool

In [235]:
whole_data.loc[existing_structure, 'pdb_file'] = whole_data.loc[existing_structure, 'meta.structure.id'].str.upper() + '.pdb'

In [236]:
whole_data.loc[existing_structure, 'pdb_file']

6986      6AVF.pdb
6988      6AVG.pdb
7076      5EU6.pdb
14525     5WKF.pdb
14526     5WKH.pdb
            ...
130414    6VRN.pdb
130415    6VQO.pdb
130418    6ULN.pdb
130419    6ULK.pdb
130420    6UON.pdb
Name: pdb_file, Length: 261, dtype: object

In [240]:
whole_data.loc[existing_structure, 'structure_type'] = 'native'

whole_data

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,20350288084b42c9b68db20e8e8f90466438e3619b6116...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...,"Fig 9, Supp Fig 5, Supp Table 5-8",NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_min.pdb,scherbinin,unknown
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_min.pdb,scherbinin,unknown
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown

In [242]:
whole_data.structure_type.unique()

array(['unmodeled', 'TCRmodel2', 'native', 'scherbinin'], dtype=object)

In [244]:
whole_data.columns

Index(['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta',
       'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq',
       'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq', 'TCR_hash',
       'meta.structure.id', 'pdb_file', 'structure_type', 'confidence'],
      dtype='object')

In [246]:
whole_data[['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta',
       'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq',
       'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq', 'pdb_file', 'structure_type', 'confidence']].to_csv('./final_table_iter_1.tsv', sep='\t')

In [250]:
whole_data[whole_data.pdb_file.apply(lambda x: pd.notnull(x))]

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,TCR_hash,meta.structure.id,pdb_file,structure_type,confidence
1159,CAMREGGSNYQLIW,TRAV14/DV4*01,TRAJ33*01,CASSMIPDMNTEAFF,TRBV19*01,TRBJ1-1*01,HomoSapiens,HLA-B*08:01,B2M,RPIIRPATL,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,e65469dacd705ce72895eba2a2429496b764a2b1757f9f...,"Fig 9, Supp Fig 5, Supp Table 5-8",aligned_e65469dacd705ce72895eba2a2429496b764a2...,TCRmodel2,validated
1162,CAMREGGGGSNYKLTF,TRAV14/DV4*01,TRAJ53*01,CASSIIPDMNTEAFF,TRBV19*01,TRBJ1-1*01,HomoSapiens,HLA-B*08:01,B2M,RPIIRPATL,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,93964a9d39918fff3b481e2e2c49e521ae6481bb1131fc...,"Fig 9, Supp Fig 5, Supp Table 5-8",aligned_93964a9d39918fff3b481e2e2c49e521ae6481...,TCRmodel2,validated
1220,CAMRGGSGGSNYKLTF,TRAV14/DV4*01,TRAJ53*01,CASSIIPDMNTEAFF,TRBV19*01,TRBJ1-1*01,HomoSapiens,HLA-B*08:01,B2M,RPIIRPATL,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,adb892c1da0bd50b6539fb0e50c763748fa957f9d426db...,"Fig 9, Supp Fig 5, Supp Table 5-8",aligned_adb892c1da0bd50b6539fb0e50c763748fa957...,TCRmodel2,validated
1237,CAMRESASGGSYIPTF,TRAV14/DV4*01,TRAJ6*01,CASSIIPDMNTEAFF,TRBV19*01,TRBJ1-1*01,HomoSapiens,HLA-B*08:01,B2M,RPIIRPATL,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,4aa699d22372356b717176ff38e6ac95e12d77a52e3c18...,"Fig 9, Supp Fig 5, Supp Table 5-8",aligned_4aa699d22372356b717176ff38e6ac95e12d77...,TCRmodel2,validated
1243,CAMREDSGGSNYKLTF,TRAV14/DV4*01,TRAJ53*01,CASSMIPDMNTEAFF,TRBV19*01,TRBJ1-1*01,HomoSapiens,HLA-B*08:01,B2M,RPIIRPATL,MSLSSLLKVVTASLWLGPGIAQKITQTQPGMFVQEKEAVTLDCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFDTAMSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,fe71db0074bc2e858c5a304d6b508745d089fda0e00c2a...,"Fig 9, Supp Fig 5, Supp Table 5-8",aligned_fe71db0074bc2e858c5a304d6b508745d089fd...,TCRmodel2,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_min.pdb,scherbinin,unknown
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_min.pdb,scherbinin,unknown
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,NaN,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown

In [252]:
additional_structures_input.columns

Index(['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta',
       'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq',
       'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq', 'pdb_file',
       'structure_type', 'confidence'],
      dtype='object')

In [255]:
merged_df['cdr3.beta'].unique()

array(['CASRPGLAGGRPEQYF', 'CASSIGQAYEQYF', 'CASSSGQAYEQYF',
       'CASSTGQAYEQYF', 'CASSVGQAYELYF', 'CASSVGQAYEQYF', 'CASSSRSSYEQYF',
       'CASSTRSSYEQYF', 'CASSTRSTHEQYF', 'CASSTRSTVEQYF', 'CASSTRSTYEQYF',
       'CASSVQSSYEQYF', 'CASSVRSAYEQYF', 'CASSVRSGHEQYF', 'CASSVRSPYEQYF',
       'CASSVRSSYEQHF', 'CASSVRSSYEQYF', 'CASSVRSSYKQYF', 'CASSVRSTYEQYF',
       'CASSYRSAYEQYF', 'CAGSSRSGHEQYF', 'CASSYRSSYEQYF', 'CVSSVRSSYEQYF',
       'CAGSTRSSYEQYF', 'CASGVRSAYEQYF', 'CASSARGAYEQYF', 'CASSARSAYEQYF',
       'CASSARSSSEQYF', 'CASSARSSTEQYF', 'CASSARSSYEQYF', 'CASSFRSGIEQYF',
       'CASSFRSSYEQYF', 'CASSGRSGIEQYF', 'CASSGRSGVEQYF', 'CASSGRSGYEQYF',
       'CASSHRSSYEQYF', 'CASSIRSGWEQYF', 'CASSKRGSYEQYF', 'CASSKRSGIEQYF',
       'CASSKRSSYEQYF', 'CASSLRSAGEQYF', 'CASSLRSAYEQYF', 'CASSLRSSYEQYF',
       'CASSMRSAHEQYF', 'CASSMRSAYEQYF', 'CASSMRSGIEQYF', 'CASSMRSGPEQYF',
       'CASSMRSGSEQYF', 'CASSMRSGVEQYF', 'CASSMRSGYEQYF', 'CASSMRSSGEQYF',
       'CASSMRSSGTQYF', 'CASSMRSSHEQYF', 'CASSMRSSWEQYF', 'CASSMRSSYEQYF',
       'CASSMRWAYEQYF', 'CASSPRSAVEQYF', 'CASSPRSAYEQYF', 'CASSPRSSYEQYF',
       'CASSQRSSYEQYF', 'CASSSRSAYEQYF', 'CASSSRSGHEQFF', 'CASSSRSGHEQYF',
       'CASSSRSGIEQFF', 'CASSSRSGIEQYF', 'CASSSRSGWEQYF', 'CASSSRSGWTQYF',
       'CASSSRSGYEQYF', 'CASSSRSQHEQYF', 'CASSSRSQVEQYF', 'CASSSRSQYEQYF',
       'CASSSRSSGEQYF', 'CASSTHSTYEQYF', 'CASSTRGAYEQYF', 'CASSTRSAYEQYF',
       'CASSTRSDYEQYF', 'CASSTRSGTEQYF', 'CASSTRSGWEQYF', 'CASSTRSGYEQYF',
       'CASSTRSSSEQYF', 'CASSTRSSTEQYF', 'CASSTRSSVEQYF',
       'CATGTGDSNQPQHF', 'CAIGTGDSNQPQHF', 'CAISTGDGNQPQHF',
       'CAISTGDSNQPQHF', 'CATGTRDSNQPQHF', 'CASSFRSGVEQYF',
       'CASSPRSGVEQYF', 'CASSSRSGVEQFF', 'CASSSRSGVEQYF', 'CASSSRASYEQYF',
       'CANSQRASYEQYF', 'CASSFRASYEQYF', 'CASSGRAAYEQYF', 'CASSGRATYEQYF',
       'CASSILASYEQYF', 'CASSIRAADEQYF', 'CASSIRAAWEQYF', 'CASSIRAAYEQYF',
       'CASSIRADDEQYF', 'CASSIRADYEQYF', 'CASSIRAGFEQYF', 'CASSIRAGVEQYF',
       'CASSIRAGWEQYF', 'CASSIRAGYEQFF', 'CASSIRAGYEQYF', 'CASSIRASVEQYF',
       'CASSIRASWEQYF', 'CASSIRASYEQYF', 'CASSIRATWEQYF', 'CASSIRATYEQYF',
       'CASSIRVGYEQYF', 'CASSIRWAYEQYF', 'CASSKRASYEQYF', 'CASSKSASYEQYF',
       'CASSLRASGAQYF', 'CASSLRASGEQYF', 'CASSLRASYEQYF', 'CASSLYASYEQYF',
       'CASSMRAAYEQYF', 'CASSMRAGGEQYF', 'CASSMRAGYEQYF', 'CASSMRASHEQYF',
       'CASSMRASVEQFF', 'CASSMRASVEQYF', 'CASSMRASYEQYF', 'CASSNRAAYEQYF',
       'CASSNRASYEQYF', 'CASSQRASYEQYF', 'CASSRRASYEQYF', 'CASSSRAAVEQYF',
       'CASSSRAAYEQYF', 'CASSSRAGGEQYF', 'CASSSRAGYEQYF', 'CASSSRASHEQYF',
       'CASSTLASYEQYF', 'CASSTRAAYEQYF', 'CASSTRAFYEQYF', 'CASSTRASYEQYF',
       'CASSVRAAWEQYF', 'CASSVRAAYEQYF', 'CASSVRASDEQYF', 'CASSVRASYEQYF',
       'CASTGSYGYTF', 'CASSATYGYTF', 'CASSGSYGYTF', 'CASSGTYGYTF',
       'CASSHTYGYTF', 'CASSISYGYTF', 'CASSLTYGYTF', 'CASSMSYGYTF',
       'CASSMTYGYTF', 'CASSNTYGYTF', 'CASSQSYGYTF', 'CASSTSYGYTF',
       'CASSTTYGYTF', 'CASTASYGYTF', 'CASTDSYGYTF', 'CASTGPYGYTF',
       'CATTDTYGYTF', 'CATTGSYGYTF', 'CATTGTYGYTF', 'CASSPVTGGIYGYTF',
       'CASSARSGELFF', 'CASSAPAGELFF', 'CASSAPTGELFF', 'CASSARTGELFF',
       'CASSSRSGELFF', 'CASSVRSGELFF', 'CASSVRTGELFF', 'CSARDGTGNGYTF',
       'CGARDGPGNGYTF', 'CGARDGTGNGYTF', 'CSARDATGNGYTF', 'CSARDETGNGYTF',
       'CSARDGKGNGYTF', 'CSARDGSGNGYTF', 'CSARDGTGNDYTF', 'CSARDKTGNGYTF',
       'CSARDQTGNDYTF', 'CSARDQTGNGYTF', 'CSARDRIGNGYTF', 'CSARDRKGNGYTF',
       'CSARDRTGNGYTF', 'CSARDRVGNGHTF', 'CSARDRVGNGYTF', 'CSARDSPGNGYTF',
       'CSARDSTGNGYTF', 'CSARDSVGNGYTF', 'CSARDTTGNGYTF', 'CSARDTVGNGYTF',
       'CSARDWTGNGYTF', 'CSAREGTGNGYTF', 'CSARGGTGNGYTF', 'CASSFGREQYF',
       'CASSEGGEQYF', 'CASSEGREQYF', 'CASSGGGEQYF', 'CASSLGDEQYF',
       'CASSLGGEQYF', 'CASSQGDEQYF', 'CASSQGDTQYF', 'CASSQGREQYF',
       'CASSTGDEQYF', 'CASSWGGEQYF', 'CASTEGGEQYF', 'CASRPGLMSAQPEQYF',
       'CASREGQGGTEAFF', 'CASREGRGGTEAFF', 'CASSLTGGGKLFF',
       'CASSLTGGGELFF', 'CASSQTQLWETQYF', 'CAGSQTQLWETQYF',
       'CANSQTQLWETQYF', 'CARSQTQLWETQYF', 'CASNQTQLWETQYF',
       'CASSKTQLWETQYF', 'CASSLSQLWETQYF', 'CASSLSQLWETRYF',
       'CASSLTQLWETQYF', 'CASSQAQLWETQYF', 'CASSQTQFWETQYF',
       'CASSQTQLWEAQYF', 'CASSQTQLWEIQYF', 'CASSQTQLWETQHF',
       'CASSQTQLWETRYF', 'CASSQTQLWGTQYF', 'CASSQTQLWKTQYF',
       'CASSQTQPWETQYF', 'CASSRTQLWETQYF', 'CDSSQTQLWETQYF',
       'CVSSQTQLWETQYF', 'CASSLAPGTTNEKLFF', 'CAGSLAPGATNEKLFF',
       'CANSLAPGATNEKLFF', 'CARSLAPGATNEKLFF', 'CASILAPGATNEKLFF',
       'CASNLAPGATNEKLFF', 'CASSLAPEATNEKLFF', 'CASSLAPGAANEKLFF',
       'CASSLAPGAINEKLFF', 'CASSLAPGATNEKLFF', 'CASSLAPGATNGKLFF',
       'CASSLAPGATNKKLFF', 'CASSLAPGATNQKLFF', 'CASSLAPGATSEKLFF',
       'CASSLAPGSTNEKLFF', 'CASSLAPGVTNEKLFF', 'CASSLAPRATNEKLFF',
       'CASSLPPEATNEKLFF', 'CASSLPPGATNEKLFF', 'CASSLTPGATNEKLFF',
       'CASSLIYPGELFF', 'CASSLIFPGELFF', 'CASSSIFPGELFF', 'CASSIRSSGEQFF',
       'CASSIRSSGPQFF', 'CASSIRSSHEQFF', 'CASSIRSSHEQYF', 'CASSIRSSHTQYF',
       'CASSIRSSLEQYF', 'CASSIRSSNEQFF', 'CASSIRSSNEQYF', 'CASSIRSSSEQFF',
       'CASSIRSSSEQYF', 'CASSIRSSTEAFF', 'CASSIRSSVEAFF', 'CASSIRSSVEQFF',
       'CASSIRSSVEQYF', 'CASSIRSSVMQYF', 'CASSIRSSWEAFF', 'CASSIRSSYEAFF',
       'CASSIRSSYEQFF', 'CASSIRSSYGQYF', 'CASSIRSSYKQYF', 'CASSIRSTAEQYF',
       'CASSIRSTETQYF', 'CASSIRSTHEQFF', 'CASSIRSTNEQFF', 'CASSIRSTSEQYF',
       'CASSIRSTVEQFF', 'CASSIRSTYEQYF', 'CASSIRSVAEQYF', 'CASSIRSVDTQYF',
       'CASSIRSVGEQYF', 'CASSIRSVHEQFF', 'CASSIRSVYEQFF', 'CASSIRSVYEQYF',
       'CASSIRTSYEQYF', 'CASSIVSSETQYF', 'CASSIYGSYEQYF', 'CASSIYSGNEQYF',
       'CASSIYSSNEQFF', 'CASSLRSSDTQYF', 'CASSLRSSNEQFF', 'CASSMRSSDTQYF',
       'CASSPRSSDTQYF', 'CASSQRSSDTQYF', 'CASSRRSGGEQYF', 'CASSRRSSDEQYF',
       'CASSSRSSDTQYF', 'CASSSRSSETQYF', 'CASSSRSSNEQFF', 'CASSSYGSYEQYF',
       'CASSTRSSNEQFF', 'CASSVRSSDTQYF', 'CASSVRSSGEQFF', 'CVSSIRSAYEQYF',
       'CASSIRSSYEQYF', 'CAGSIRSSYEQYF', 'CANSIRSSYEQYF', 'CASGIRSSYEQYF',
       'CASIIRSSYEQYF', 'CASNIRSSYEQYF', 'CASSARGSGEQYF', 'CASSARSSDTQYF',
       'CASSARSSGEQFF', 'CASSARSSNEQFF', 'CASSFRSSETQYF', 'CASSGRSSDTQYF',
       'CASSIFGSYEQYF', 'CASSIISSYEQYF', 'CASSIRASDTQYF', 'CASSIRASETQYF',
       'CASSIRASHEQFF', 'CASSIRASNEQFF', 'CASSIRGAHEQYF', 'CASSIRGAYEQYF',
       'CASSIRGGYEQYF', 'CASSIRGSDEQYF', 'CASSIRGSDTQYF', 'CASSIRGSETQYF',
       'CASSIRGSGEQYF', 'CASSIRGSYEQYF', 'CASSIRNSYEQYF', 'CASSIRPSYEQYF',
       'CASSIRSADEQYF', 'CASSIRSADTQYF', 'CASSIRSAETQYF', 'CASSIRSAHEQFF',
       'CASSIRSAHEQYF', 'CASSIRSAIEQYF', 'CASSIRSAWEQFF', 'CASSIRSAYEQFF',
       'CASSIRSAYEQYF', 'CASSIRSAYERYF', 'CASSIRSDNEQFF', 'CASSIRSDYEQYF',
       'CASSIRSEDTQYF', 'CASSIRSEYEQYF', 'CASSIRSFYEQYF', 'CASSIRSGAEQYF',
       'CASSIRSGATQYF', 'CASSIRSGDTQYF', 'CASSIRSGEEQYF', 'CASSIRSGETQYF',
       'CASSIRSGFEQFF', 'CASSIRSGGEQFF', 'CASSIRSGGEQYF', 'CASSIRSGHEQFF',
       'CASSIRSGHEQYF', 'CASSIRSGIEQFF', 'CASSIRSGNEQFF', 'CASSIRSGNEQYF',
       'CASSIRSGNIQYF', 'CASSIRSGSEQFF', 'CASSIRSGVEQFF', 'CASSIRSGVEQYF',
       'CASSIRSGVIQYF', 'CASSIRSGWEQFF', 'CASSIRSGYEQFF', 'CASSIRSGYEQYF',
       'CASSIRSHDEQFF', 'CASSIRSHYEQYF', 'CASSIRSLDTQYF', 'CASSIRSNGEQFF',
       'CASSIRSNNEQFF', 'CASSIRSNYEQYF', 'CASSIRSPYEQYF', 'CASSIRSQDTQYF',
       'CASSIRSQETQYF', 'CASSIRSQVEQFF', 'CASSIRSSAEAFF', 'CASSIRSSCEQYF',
       'CASSIRSSDEQFF', 'CASSIRSSDEQYF', 'CASSIRSSDTQYF', 'CASSIRSSEEQYF',
       'CASSIRSSETQYF', 'CASSIRSSFEAFF', 'CASSIRSSGELFF', 'CASSIFGQGEQYF',
       'CASSIFGQGTQYF', 'CASSIGVYGYTF', 'CAASTGNYGYTF', 'CAASTGSYGYTF',
       'CASSAGAYGYTF', 'CASSAGLYGYTF', 'CASSAGSYGYTF', 'CASSEGSYGYTF',
       'CASSFGIYGYTF', 'CASSFGLHGYTF', 'CASSFGLYGYTF', 'CASSFGMHGYTF',
       'CASSFGSHGYTF', 'CASSFGSYGYTF', 'CASSFGVHGYTF', 'CASSHGSYGYTF',
       'CASSIGAHGYTF', 'CASSIGAWGYTF', 'CASSIGAYGYTF', 'CASSIGAYRYTF',
       'CASSIGEYGYTF', 'CASSIGFYGYTF', 'CASSIGHYGYTF', 'CASSIGIHGYTF',
       'CASSIGIYGYTF', 'CASSIGLFGYTF', 'CASSIGLIGYTF', 'CASSIGLWGYTF',
       'CASSIGLYGYTF', 'CASSIGMHGYTF', 'CASSIGNYGYTF', 'CASSIGSHGYTF',
       'CASSIGSYGSTF', 'CASSIGSYGYTF', 'CASSIGTYGYTF', 'CASSIGVAGYTF',
       'CASSIGVHGYTF', 'CASSIGVWGYTF', 'CASSIGWHGYTF', 'CASSIGWNGYTF',
       'CASSIGWSGYTF', 'CASSIGYHGYTF', 'CASSIGYYGYTF', 'CASSIVVHGYTF',
       'CASSLGAYGYTF', 'CASSLGLYGYTF', 'CASSLGSFGYTF', 'CASSLGSYGYTF',
       'CASSMGAYGYTF', 'CASSMGIYGYTF', 'CASSMGLYGYTF', 'CASSMGNYGYTF',
       'CASSMGSHGYTF', 'CASSMGSVGYTF', 'CASSMGSYGYTF', 'CASSNGAYGYTF',
       'CASSQGAFGYTF', 'CASSQGAHGYTF', 'CASSQGAYGYTF', 'CASSQGFYGYTF',
       'CASSQGNYGYTF', 'CASSQGSWGYTF', 'CASSQGSYGYTF', 'CASSSGAYGYTF',
       'CASSSGSYGYTF', 'CASSTGAWGYTF', 'CASSTGAYGYTF', 'CASSTGFYGYTF',
       'CASSTGIYGYTF', 'CASSTGLWGYTF', 'CASSTGLYGYTF', 'CASSTGNYGYTF',
       'CASSTGSYGCTF', 'CASSTGSYGYTF', 'CASSTGVYGYTF', 'CASSTGYYGYTF',
       'CASSVGIYGYTF', 'CASSVGSYGYTF', 'CASSVGWYGYTF', 'CASSWGAYGYTF',
       'CASSWGSWGYTF', 'CASSWGSYGYTF', 'CASSYGSYGYTF', 'CASSYGVYGYTF',
       'CPSSIGVYGYTF', 'CASSQGLAGAGELFF', 'CASSAGLDAEQYF',
       'CASSDWGATGQLYF', 'CASSDWGGTGQLYF', 'CASSDWGNTGQLYF',
       'CASSQDLFTGGYTF', 'CASSPDIEQYF', 'CASSADIEAFF', 'CASSADIEQFF',
       'CASSADIEQYF', 'CASSADIQQYF', 'CASSDDIEAFF', 'CASSHDIEAFF',
       'CASSLDIEAFF', 'CASSLDIEQYF', 'CASSLDIETYF', 'CASSLDVEQYF',
       'CASSLEIEQYF', 'CASSPDGEQYF', 'CASSPDIDQFF', 'CASSPDIEAFF',
       'CASSPDIEDFF', 'CASSPDIEQFF', 'CASSPDIGAFF', 'CASSPDILAFF',
       'CASSPDIQAFF', 'CASSPDITQYF', 'CASSPDIVAFF', 'CASSPDSEQYF',
       'CASSPDVEAFF', 'CASSPEIEAFF', 'CASSQDIEAFF', 'CASSQDIEQYF',
       'CASSRDIEAFF', 'CASSSDIEAFF', 'CASSSDIEQFF', 'CASSSDIEQYF',
       'CASSSDIQQFF', 'CASSTDIEAFF', 'CASSVDIEAFF', 'CASSWDIEAFF',
       'CAGQVTNTGELFF'], dtype=object)

In [262]:
np.logical_and(np.array([True, True, True]), np.array([True, True, False]), np.array([False, True, False]))

array([ True,  True, False])

In [263]:
full_db = pd.read_csv('./vdjdb_full_scored.txt', sep='\t')
full_db

Columns (5,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30) have mixed types. Specify dtype option on import or set low_memory=False.

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,d.beta,j.beta,species,mhc.a,mhc.b,...,meta.clone.id,meta.epitope.id,meta.tissue,meta.donor.MHC,meta.donor.MHC.method,meta.structure.id,cdr3fix.alpha,cdr3fix.beta,vdjdb.score,cluster.member
0,NaN,NaN,NaN,CASSIVGGNEQFF,TRBV19*01,NaN,TRBJ2-1*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIVGGNEQFF', 'cdr3_old': 'CASSIVG...",3,1
1,NaN,NaN,NaN,CASSMRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSMRSTGELFF', 'cdr3_old': 'CASSMRS...",3,1
2,NaN,NaN,NaN,CASSIRSAWAQYF,TRBV19*01,NaN,TRBJ2-3*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSAWAQYF', 'cdr3_old': 'CASSIRS...",2,0
3,NaN,NaN,NaN,CASSQRSTGELFF,TRBV19*01,NaN,TRBJ2-2*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSQRSTGELFF', 'cdr3_old': 'CASSQRS...",2,1
4,NaN,NaN,NaN,CASSIRSSYEQYF,TRBV19*01,NaN,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,...,NaN,M158–66,PBMC,"A02,A03,B07,B27,C01,C07",NaN,NaN,NaN,"{'cdr3': 'CASSIRSSYEQYF', 'cdr3_old': 'CASSIRS...",3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131941,NaN,NaN,NaN,CASSPSARGNQPQHF,TRBV2*01,TRBD1*01,TRBJ1-5*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSPSARGNQPQHF', 'cdr3_old': 'CASSP...",0,0
131942,NaN,NaN,NaN,CASSVGTSGVGEQYF,TRBV2*01,TRBD2*01,TRBJ2-7*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB5*01:01,...,NaN,NaN,NaN,"DRB1*0102,DRB1*1101",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSVGTSGVGEQYF', 'cdr3_old': 'CASSV...",0,0
131943,NaN,NaN,NaN,CASSALASGGDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSALASGGDTQYF', 'cdr3_old': 'CASSA...",0,1
131944,NaN,NaN,NaN,CASSRLAGGMDEQFF,TRBV2*01,TRBD2*02,TRBJ2-1*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRLAGGMDEQFF', 'cdr3_old': 'CASSR...",3,1
131945,NaN,NaN,NaN,CASSRRTSGGTDTQYF,TRBV2*01,TRBD2*01,TRBJ2-3*01,HomoSapiens,HLA-DRA*01:01,HLA-DRB1*15:02,...,NaN,NaN,NaN,"DRB1*0701/ 0703/0704/ 0705/ 0706,DRB1*1501/ 15...",INNO-LiPA HLA-DRB1 Plus kit,NaN,NaN,"{'cdr3': 'CASSRRTSGGTDTQYF', 'cdr3_old': 'CASS...",2,1

In [265]:
np.nan + 1

nan

In [266]:
test_df = pd.DataFrame()

test_df

Empty DataFrame
Columns: []
Index: []

In [272]:
test_df['my_test_none'] = None

test_df['my_test_array'] = pd.Series([0, 1, 2, 3])
test_df['my_test_int'] = 1

In [273]:
test_df

  my_test_none  my_test_int  my_test_array
0         None            1              0
1         None            1              1
2         None            1              2
3         None            1              3

In [274]:
test_df.my_test_none + test_df.my_test_int

0    NaN
1    NaN
2    NaN
3    NaN
dtype: object

# Error check

In [3]:
data2_generate = pd.read_csv('./HomoSapiens_MHCI_all_clusters_chunk_3.tsv', sep='\t')
data2_generate

,Unnamed: 0,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
0,48720,CAVGDDKIIF,TRAV12-2*01,TRAJ30*01,CASVPFSGNTIYF,TRBV19*01,TRBJ1-3*01,KLGGALQAK,HLA-A*03:01,B2M,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGDDKIIFTRAV12-2*01TRAJ30*01CASVPFSGNTIYFTRB...,b0c61fd66785f11a1082c7c67e868e2be337e4c85ee49c...,HLA-A,TCRmodel_no_relax
1,48723,CVVEAGANNLFF,TRAV12-1*01,TRAJ36*01,CAISEMAGGGTDTQYF,TRBV10-3*01,TRBJ2-3*01,KLGGALQAK,HLA-A*03:01,B2M,MISLRVLLVILWLQLSWVWSQRKEVEQDPGPFNVPEGATVAFNCTY...,MGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPVTLRCHQTE...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CVVEAGANNLFFTRAV12-1*01TRAJ36*01CAISEMAGGGTDTQ...,b35c2f682105fefffd9116512c43585e4dddd8c0558cb4...,HLA-A,TCRmodel_no_relax
2,48724,CAFMNSGYALNF,TRAV38-1*01,TRAJ41*01,CASSAGTSGDNEQFF,TRBV9*01,TRBJ2-1*01,KLGGALQAK,HLA-A*03:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMNSGYALNFTRAV38-1*01TRAJ41*01CASSAGTSGDNEQF...,da359692d4a445638fafd907c8e40e7eb15737cce5fbb7...,HLA-A,TCRmodel_no_relax
3,48725,CAVVWMEYGNKLVF,TRAV8-3*01,TRAJ47*01,CASSSRTDYGYTF,TRBV7-9*01,TRBJ1-2*01,KLGGALQAK,HLA-A*03:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVVWMEYGNKLVFTRAV8-3*01TRAJ47*01CASSSRTDYGYTF...,9fecbed852009caa0b9db56862bbb798d2102d3b40b797...,HLA-A,TCRmodel_no_relax
4,48732,CAGLTGNQFYF,TRAV12-2*01,TRAJ49*01,CSVQTGRAFF,TRBV20-1*01,TRBJ1-1*01,KLGGALQAK,HLA-A*03:01,B2M,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGLTGNQFYFTRAV12-2*01TRAJ49*01CSVQTGRAFFTRBV2...,0707df59fb648a06d09131ee62921499e1d95726a3ec41...,HLA-A,TCRmodel_no_relax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,91519,CAVGATGNQFYF,TRAV8-3*01,TRAJ49*01,CASSTTGFSYEQYF,TRBV7-9*01,TRBJ2-7*01,NLVPMVATV,HLA-A*02:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGATGNQFYFTRAV8-3*01TRAJ49*01CASSTTGFSYEQYFT...,0b6e3be392956d9c754c034b031b15edbf615bb97847d6...,HLA-A,TCRmodel_no_relax
2996,91534,CAVFKAAGNKLTF,TRAV8-6*01,TRAJ17*01,CASSPTTEIHGNTIYF,TRBV12-3*01,TRBJ1-3*01,NLVPMVATV,HLA-A*02:01,B2M,MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...,MDSWTFCCVSLCILVAKHTDAGVIQSPRHEVTEMGQEVTLRCKPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVFKAAGNKLTFTRAV8-6*01TRAJ17*01CASSPTTEIHGNTI...,6b428d6c7e82f8ad2881d92a7fed1d52c71ae5d89d3f7f...,HLA-A,TCRmodel_no_relax
2997,91536,CATNSGYALNF,TRAV21*01,TRAJ41*01,CASRTATTEAFF,TRBV7-9*01,TRBJ1-1*01,NLVPMVATV,HLA-A*02:01,B2M,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CATNSGYALNFTRAV21*01TRAJ41*01CASRTATTEAFFTRBV7...,95353882e43242dd0f07f2f47ad3569765400c0871c192...,HLA-A,TCRmodel_no_relax
2998,91538,CAVGDTNAGKSTF,TRAV8-3*01,TRAJ27*01,CASSLVLTGGAYGYTF,TRBV7-2*01,TRBJ1-2*01,NLVPMVATV,HLA-A*02:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGDTNAGKSTFTRAV8-3*01TRAJ27*01CASSLVLTGGAYGY...,7aed014a4c05950d9d66f22454d0742b3ac8f39111a4c4...,HLA-A,TCRmodel_no_relax
2999,91540,CAFRDSGGYQKVTF,TRAV24*01,TRAJ13*01,CASSLGSSYEQYF,TRBV7-9*01,TRBJ2-7*01,NLVPMVATV,HLA-A*02:01,B2M,MEKNPLAAPLLILWFHLDCVSSILNVEQSPQSLHVQEGDSTNFTCS...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFRDSGGYQKVTFTRAV24*01TRAJ13*01CASSLGSSYEQYFT...,6c7fa87f4e47ebee0db1aeba954ef7a8c926442c134868...,HLA-A,TCRmodel_no_relax

In [5]:
data2_generate['mhc.aa.seq'].unique()

array(['MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAQSQTDRVDLGTLRGYYNQSEAGSHTIQIMYGCDVGSDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAAHEAEQLRAYLDGTCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWELSSQPTIPIVGIIAGLVLLGAVITGAVVAAVMWRRKSSDRKGGSYTQAASSDSAQGSDVSLTACKV',
       'MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHRVDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAAHVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAVSDHEATLRCWALSFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLPKPLTLRWEPSSQPTIPIVGIIAGLVLFGAVITGAVVAAVMWRRKSSDRKGGSYSQAASSDSAQGSDVSLTACKV',
       'MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFYTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDQETRNVKAQSQTDRVDLGTLRGYYNQSEDGSHTIQIMYGCDVGPDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAAHAAEQQRAYLEGRCVEWLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWELSSQPTIPIVGIIAGLVLLGAVITGAVVAAVMWRRKSSDRKGGSYTQAASSDSAQGSDVSLTACKV',
       'MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQKMEPRAPWIEQEGPEYWDQETRNMKAHSQTDRANLGTLRGYYNQSEDGSHTIQIMYGCDVGPDGRFLRGYRQDAYDGKDYIALNEDLRSWTAADMAAQITKRKWEAVHAAEQRRVYLEGRCVDGLRRYLENGKETLQRTDPPKTHMTHHPISDHEATLRCWALGFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGEEQRYTCHVQHEGLPKPLTLRWELSSQPTIPIVGIIAGLVLLGAVITGAVVAAVMWRRKSSDRKGGSYTQAASSDSAQGSDVSLTACKV'],
      dtype=object)

In [23]:
data_to_generate_1 = pd.read_csv('./HomoSapiens_MHCI_all_clusters_chunk_1.tsv', sep='\t', index_col=0)
data_to_generate_1

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
3508,CAGSYGGSQGNLIF,TRAV35*01,TRAJ42*01,CASSVRSSGEQFF,TRBV19*01,TRBJ2-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGSYGGSQGNLIFTRAV35*01TRAJ42*01CASSVRSSGEQFFT...,0b503b58a7567ceeed312bbd3284ea683bfaa3a9134384...,HLA-A,TCRmodel_no_relax
3509,CAGPDGSSNTGKLIF,TRAV35*01,TRAJ37*01,CASSLIFPGRAFF,TRBV27*01,TRBJ1-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGPDGSSNTGKLIFTRAV35*01TRAJ37*01CASSLIFPGRAFF...,8676fcdbea24492db07eb1e0b73a923cb490a7ffeae47a...,HLA-A,TCRmodel_no_relax
3510,CAFMVNAGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGSYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMVNAGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGSYG...,936577cc40fa11349a5d8a6df30a44c123312d921cd30d...,HLA-A,TCRmodel_no_relax
3511,CAYSPASGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGLYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAYSPASGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGLYG...,c988791e011fe924c9ace35f30961c5d6152a934d10dea...,HLA-A,TCRmodel_no_relax
3512,CAEDNNARLMF,TRAV5*01,TRAJ31*01,CSARVGVGNTIYF,TRBV20-1*01,TRBJ1-3*01,GLCTLVAML,HLA-A*02:01,B2M,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAEDNNARLMFTRAV5*01TRAJ31*01CSARVGVGNTIYFTRBV2...,d0ff9f35e47e8e0d862d9cee9e87a0d30c094524931382...,HLA-A,TCRmodel_no_relax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40162,CAVRVDSNYQLIW,TRAV41*01,TRAJ33*01,CASSQAGGLFEQYF,TRBV4-3*01,TRBJ2-7*01,KLGGALQAK,HLA-A*03:01,B2M,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGCRLLCCAVLCLLGAGELVPMETGVTQTPRHLVMGMTNKKSLKCE...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVRVDSNYQLIWTRAV41*01TRAJ33*01CASSQAGGLFEQYFT...,6768d474f8e144051d7925102d48136c50aa3cfbe29ad9...,HLA-A,TCRmodel_no_relax
40166,CAVSSQGGSEKLVF,TRAV21*01,TRAJ57*01,CSVDQGGGRMGESYTF,TRBV29-1*01,TRBJ1-2*01,KLGGALQAK,HLA-A*03:01,B2M,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVSSQGGSEKLVFTRAV21*01TRAJ57*01CSVDQGGGRMGESY...,162c9435a4fccb0f0718bbc57e1838bb74da39fc01a267...,HLA-A,TCRmodel_no_relax
40169,CAVNSDYKLSF,TRAV1-2*01,TRAJ20*01,CSAGQGPNTGELFF,TRBV20-1*01,TRBJ2-2*01,KLGGALQAK,HLA-A*03:01,B2M,MWGVFLLYVSMKMGGTTGQNIDQPTEMTATEGAIVQINCTYQTSGF...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVNSDYKLSFTRAV1-2*01TRAJ20*01CSAGQGPNTGELFFTR...,5f41aae24eb1f4ea278ddd757f7eab0a0f741069b5b4b5...,HLA-A,TCRmodel_no_relax
40170,CALIQGAQKLVF,TRAV38-1*01,TRAJ54*01,CASSPATGGHQPQHF,TRBV6-5*01,TRBJ1-5*01,KLGGALQAK,HLA-A*03:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CALIQGAQKLVFTRAV38-1*01TRAJ54*01CASSPATGGHQPQH...,277403a1734b6a592064ff8120aa0e32c1efbd3d463fa8...,HLA-A,TCRmodel_no_relax
40172,CALSRAGANSKLTF,TRAV9-2*01,TRAJ56*01,CASSPHARDRVRGNTEAFF,TRBV5-1*01,TRBJ1-1*01,KLGGALQAK,HLA-A*03:01,B2M,MNYSPGLVSLILLLLGRTRGNSVTQMEGPVTLSEEAFLTINCTYTA...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CALSRAGANSKLTFTRAV9-2*01TRAJ56*01CASSPHARDRVRG...,929ebcb427bad25ee226e5b956b9df0b6ea9ef087220d1...,HLA-A,TCRmodel_no_relax

In [24]:
data_to_generate_3 = pd.read_csv('./HomoSapiens_MHCI_all_clusters_chunk_3.tsv', sep='\t', index_col=0)
data_to_generate_3

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
48720,CAVGDDKIIF,TRAV12-2*01,TRAJ30*01,CASVPFSGNTIYF,TRBV19*01,TRBJ1-3*01,KLGGALQAK,HLA-A*03:01,B2M,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGDDKIIFTRAV12-2*01TRAJ30*01CASVPFSGNTIYFTRB...,b0c61fd66785f11a1082c7c67e868e2be337e4c85ee49c...,HLA-A,TCRmodel_no_relax
48723,CVVEAGANNLFF,TRAV12-1*01,TRAJ36*01,CAISEMAGGGTDTQYF,TRBV10-3*01,TRBJ2-3*01,KLGGALQAK,HLA-A*03:01,B2M,MISLRVLLVILWLQLSWVWSQRKEVEQDPGPFNVPEGATVAFNCTY...,MGTRLFFYVALCLLWTGHMDAGITQSPRHKVTETGTPVTLRCHQTE...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CVVEAGANNLFFTRAV12-1*01TRAJ36*01CAISEMAGGGTDTQ...,b35c2f682105fefffd9116512c43585e4dddd8c0558cb4...,HLA-A,TCRmodel_no_relax
48724,CAFMNSGYALNF,TRAV38-1*01,TRAJ41*01,CASSAGTSGDNEQFF,TRBV9*01,TRBJ2-1*01,KLGGALQAK,HLA-A*03:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMNSGYALNFTRAV38-1*01TRAJ41*01CASSAGTSGDNEQF...,da359692d4a445638fafd907c8e40e7eb15737cce5fbb7...,HLA-A,TCRmodel_no_relax
48725,CAVVWMEYGNKLVF,TRAV8-3*01,TRAJ47*01,CASSSRTDYGYTF,TRBV7-9*01,TRBJ1-2*01,KLGGALQAK,HLA-A*03:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVVWMEYGNKLVFTRAV8-3*01TRAJ47*01CASSSRTDYGYTF...,9fecbed852009caa0b9db56862bbb798d2102d3b40b797...,HLA-A,TCRmodel_no_relax
48732,CAGLTGNQFYF,TRAV12-2*01,TRAJ49*01,CSVQTGRAFF,TRBV20-1*01,TRBJ1-1*01,KLGGALQAK,HLA-A*03:01,B2M,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGLTGNQFYFTRAV12-2*01TRAJ49*01CSVQTGRAFFTRBV2...,0707df59fb648a06d09131ee62921499e1d95726a3ec41...,HLA-A,TCRmodel_no_relax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91519,CAVGATGNQFYF,TRAV8-3*01,TRAJ49*01,CASSTTGFSYEQYF,TRBV7-9*01,TRBJ2-7*01,NLVPMVATV,HLA-A*02:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGATGNQFYFTRAV8-3*01TRAJ49*01CASSTTGFSYEQYFT...,0b6e3be392956d9c754c034b031b15edbf615bb97847d6...,HLA-A,TCRmodel_no_relax
91534,CAVFKAAGNKLTF,TRAV8-6*01,TRAJ17*01,CASSPTTEIHGNTIYF,TRBV12-3*01,TRBJ1-3*01,NLVPMVATV,HLA-A*02:01,B2M,MLLLLVPAFQVIFTLGGTRAQSVTQLDSQVPVFEEAPVELRCNYSS...,MDSWTFCCVSLCILVAKHTDAGVIQSPRHEVTEMGQEVTLRCKPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVFKAAGNKLTFTRAV8-6*01TRAJ17*01CASSPTTEIHGNTI...,6b428d6c7e82f8ad2881d92a7fed1d52c71ae5d89d3f7f...,HLA-A,TCRmodel_no_relax
91536,CATNSGYALNF,TRAV21*01,TRAJ41*01,CASRTATTEAFF,TRBV7-9*01,TRBJ1-1*01,NLVPMVATV,HLA-A*02:01,B2M,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CATNSGYALNFTRAV21*01TRAJ41*01CASRTATTEAFFTRBV7...,95353882e43242dd0f07f2f47ad3569765400c0871c192...,HLA-A,TCRmodel_no_relax
91538,CAVGDTNAGKSTF,TRAV8-3*01,TRAJ27*01,CASSLVLTGGAYGYTF,TRBV7-2*01,TRBJ1-2*01,NLVPMVATV,HLA-A*02:01,B2M,MLLELIPLLGIHFVLRTARAQSVTQPDIHITVSEGASLELRCNYSY...,MGTRLLFWVAFCLLGADHTGAGVSQSPSNKVTEKGKDVELRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVGDTNAGKSTFTRAV8-3*01TRAJ27*01CASSLVLTGGAYGY...,7aed014a4c05950d9d66f22454d0742b3ac8f39111a4c4...,HLA-A,TCRmodel_no_relax
91540,CAFRDSGGYQKVTF,TRAV24*01,TRAJ13*01,CASSLGSSYEQYF,TRBV7-9*01,TRBJ2-7*01,NLVPMVATV,HLA-A*02:01,B2M,MEKNPLAAPLLILWFHLDCVSSILNVEQSPQSLHVQEGDSTNFTCS...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFRDSGGYQKVTFTRAV24*01TRAJ13*01CASSLGSSYEQYFT...,6c7fa87f4e47ebee0db1aeba954ef7a8c926442c134868...,HLA-A,TCRmodel_no_relax

In [30]:
data_to_generate_3['antigen.epitope'].iloc[-1] #== data_to_generate_1['mhc.aa.seq'].iloc[0]

'NLVPMVATV'

In [14]:
broken_example = data_to_generate_total[data_to_generate_total.TCR_hash == 'e73ee9197e7d66bab1f6519f63280b8a80c6990b19facbb33b973d4d90bee9d5'].iloc[0]
broken_example

Unnamed: 0                                                       91546
cdr3.alpha                                                CATDNYGQNFVF
v.alpha                                                       TRAV2*01
j.alpha                                                      TRAJ26*01
cdr3.beta                                        CASSLGARRGVQGAAYNEQFF
v.beta                                                      TRBV7-3*01
j.beta                                                      TRBJ2-1*01
antigen.epitope                                              NLVPMVATV
mhc.a                                                      HLA-A*02:01
mhc.b                                                              B2M
TRA_aa_seq           MALQSTLGAVWLGLLLNSLWKVAESKDQVFQPSTVASSEGAVVEIF...
TRB_aa_seq           MGTRLLCWAALCLLGADHTGAGVSQTPSNKVTEKGKYVELRCDPIS...
mhc.a.short                                                HLA-A*02:01
mhc.aa.seq           MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...
index_seq            CATDNYGQNFVFTRAV2*01TRAJ26*01CASSLGARRGVQGAAYN...
TCR_hash             e73ee9197e7d66bab1f6519f63280b8a80c6990b19facb...
hla_gene                                                         HLA-A
generation_method                                    TCRmodel_no_relax
Name: 9000, dtype: object

In [15]:
data_to_generate_total[data_to_generate_total['mhc.aa.seq'] == broken_example['mhc.aa.seq']]

,Unnamed: 0,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
15,3467,CAVRDGTANNLFF,TRAV3*01,TRAJ36*01,CASSISSTGELFF,TRBV19*01,TRBJ2-2*01,GILGFVFTL,HLA-A*02:01,B2M,MASAPISMLAMLFTLSGLRAQSVAQPEDQVNVAEGNPLTVKCTYSV...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVRDGTANNLFFTRAV3*01TRAJ36*01CASSISSTGELFFTRB...,b50caece97fa5d7ac64724af76ca559c56f46497150843...,HLA-A,TCRmodel_no_relax
16,3468,CAFMKDAGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGVYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMKDAGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGVYG...,097ed7e33d0045419e9678e976751c17831b7af52b3426...,HLA-A,TCRmodel_no_relax
17,3469,CAGGGSQGNLIF,TRAV27*01,TRAJ42*01,CASSIRSSYEQYF,TRBV19*01,TRBJ2-7*01,GILGFVFTL,HLA-A*02:01,B2M,MVLKFSVSILWIQLAWVSTQLLEQSPQFLSIQEGENLTVYCNSSSV...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGGGSQGNLIFTRAV27*01TRAJ42*01CASSIRSSYEQYFTRB...,3fab22528c71e3b1dbae4f7f54d52d14f098b80eae5dac...,HLA-A,TCRmodel_no_relax
18,3470,CALAGSQGNLIF,TRAV23/DV6*01,TRAJ42*01,CASSIRASYEQYF,TRBV19*01,TRBJ2-7*01,GILGFVFTL,HLA-A*02:01,B2M,MDKILGASFLVLWLQLCWVSGQQKEKSDQQQVKQSPQSLIVQKGGI...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CALAGSQGNLIFTRAV23/DV6*01TRAJ42*01CASSIRASYEQY...,3c538d5f192d4ff8d82a2fa1c2fe9a64fc7f975598fb1d...,HLA-A,TCRmodel_no_relax
19,3471,CAGADGGSQGNLIF,TRAV27*01,TRAJ42*01,CASSGRAAGELFF,TRBV19*01,TRBJ2-2*01,GILGFVFTL,HLA-A*02:01,B2M,MVLKFSVSILWIQLAWVSTQLLEQSPQFLSIQEGENLTVYCNSSSV...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGADGGSQGNLIFTRAV27*01TRAJ42*01CASSGRAAGELFFT...,af3b3da74952a941f6e9d7a9af81c9f4f2b7992e470fa2...,HLA-A,TCRmodel_no_relax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13604,126156,CILSNNNDMRF,TRAV26-2*01,TRAJ43*01,CAWTISDLAKNIQYF,TRBV30*01,TRBJ2-4*01,NLVPMVATV,HLA-A*02:01,B2M,MKLVTSITVLLSLGIMGDAKTTQPNSMESNEEEPVHLPCNHSTISG...,MLCSLLALLLGTFFGVRSQTIHQWPATLVQPVGSPLSLECTVEGTS...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CILSNNNDMRFTRAV26-2*01TRAJ43*01CAWTISDLAKNIQYF...,d97e8ca35e26169faac35d69e382845f9ae11c1bcd6e48...,HLA-A,TCRmodel_no_relax
13605,126330,CAVRIGSQGNLIF,TRAV12-1*01,TRAJ42*01,CASSLLQGTEAFF,TRBV27*01,TRBJ1-1*01,IMDQVPFSV,HLA-A*02:01,B2M,MISLRVLLVILWLQLSWVWSQRKEVEQDPGPFNVPEGATVAFNCTY...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVRIGSQGNLIFTRAV12-1*01TRAJ42*01CASSLLQGTEAFF...,337f91e8cc2523a46016a8d42b590b99e01e144963e43d...,HLA-A,TCRmodel_no_relax
13706,131357,CAESTSWGKLQF,TRAV5*01,TRAJ24*02,CSVGTGGTNEKLFF,TRBV29-1*01,TRBJ1-4*01,GLCTLVAML,HLA-A*02:01,B2M,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAESTSWGKLQFTRAV5*01TRAJ24*02CSVGTGGTNEKLFFTRB...,d38886ada340044741c2232672f03f5f4fab1ea10c6d95...,HLA-A,TCRmodel_no_relax
13707,131358,CAILMDSNYQLIW,TRAV21*01,TRAJ33*01,CASSEDGMNTEAFF,TRBV10-2*01,TRBJ1-1*01,CLGGLLTMV,HLA-A*02:01,B2M,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MGTRLFFYVALCLLWAGHRDAGITQSPRYKITETGRQVTLMCHQTW...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAILMDSNYQLIWTRAV21*01TRAJ33*01CASSEDGMNTEAFFT...,3ce00553b3f6ffa22057cb93dd5cf8cecc43b5267fa3c1...,HLA-A,TCRmodel_no_relax
13708,131360,CATVGNSGYSTLTF,TRAV17*01,TRAJ11*01,CASSKQGGNIQYF,TRBV6-5*01,TRBJ2-4*01,FLYALALLL,HLA-A*02:01,B2M,METLLGVSLVILWLQLARVNSQQGEEDPQALSIQEGENATMNCSYK...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CATVGNSGYSTLTFTRAV17*01TRAJ11*01CASSKQGGNIQYFT...,2c40e1f3b02f9cbb6acce0edcfce8d70d3a2d0302e6919...,HLA-A,TCRmodel_no_relax

In [19]:
#data_to_generate_total.iloc[-1]['mhc.aa.seq'] ==  
broken_example['mhc.aa.seq'] == 'MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRFIAVGYVDDTQFVRFDSDAASQRMEPRAPWIEQEGPEYWDGETRKVKAHSQTHRVDLGTLRGYYNQSEAGSHTVQRMYGCDVGSDWRFLRGYHQYAYDGKDYIALKEDLRSWTAADMAAQTTKHKWEAAHVAEQLRAYLEGTCVEWLRRYLENGKETLQRTDAPKTHMTHHAVSDHEATLRCWALSFYPAEITLTWQRDGEDQTQDTELVETRPAGDGTFQKWAAVVVPSGQEQRYTCHVQHEGLPKPLTLRWEPSSQPTIPIVGIIAGLVLFGAVITGAVVAAVMWRRKSSDRKGGSYSQAASSDSAQGSDVSLTACKV'

True

In [31]:
data_to_generate_1 = pd.read_csv('./HomoSapiens_MHCI_all_clusters_chunk_1.tsv', sep='\t', index_col=0)
data_to_generate_1

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
3508,CAGSYGGSQGNLIF,TRAV35*01,TRAJ42*01,CASSVRSSGEQFF,TRBV19*01,TRBJ2-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGSYGGSQGNLIFTRAV35*01TRAJ42*01CASSVRSSGEQFFT...,0b503b58a7567ceeed312bbd3284ea683bfaa3a9134384...,HLA-A,TCRmodel_no_relax
3509,CAGPDGSSNTGKLIF,TRAV35*01,TRAJ37*01,CASSLIFPGRAFF,TRBV27*01,TRBJ1-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGPDGSSNTGKLIFTRAV35*01TRAJ37*01CASSLIFPGRAFF...,8676fcdbea24492db07eb1e0b73a923cb490a7ffeae47a...,HLA-A,TCRmodel_no_relax
3510,CAFMVNAGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGSYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMVNAGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGSYG...,936577cc40fa11349a5d8a6df30a44c123312d921cd30d...,HLA-A,TCRmodel_no_relax
3511,CAYSPASGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGLYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAYSPASGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGLYG...,c988791e011fe924c9ace35f30961c5d6152a934d10dea...,HLA-A,TCRmodel_no_relax
3512,CAEDNNARLMF,TRAV5*01,TRAJ31*01,CSARVGVGNTIYF,TRBV20-1*01,TRBJ1-3*01,GLCTLVAML,HLA-A*02:01,B2M,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAEDNNARLMFTRAV5*01TRAJ31*01CSARVGVGNTIYFTRBV2...,d0ff9f35e47e8e0d862d9cee9e87a0d30c094524931382...,HLA-A,TCRmodel_no_relax
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40162,CAVRVDSNYQLIW,TRAV41*01,TRAJ33*01,CASSQAGGLFEQYF,TRBV4-3*01,TRBJ2-7*01,KLGGALQAK,HLA-A*03:01,B2M,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGCRLLCCAVLCLLGAGELVPMETGVTQTPRHLVMGMTNKKSLKCE...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVRVDSNYQLIWTRAV41*01TRAJ33*01CASSQAGGLFEQYFT...,6768d474f8e144051d7925102d48136c50aa3cfbe29ad9...,HLA-A,TCRmodel_no_relax
40166,CAVSSQGGSEKLVF,TRAV21*01,TRAJ57*01,CSVDQGGGRMGESYTF,TRBV29-1*01,TRBJ1-2*01,KLGGALQAK,HLA-A*03:01,B2M,METLLGLLILWLQLQWVSSKQEVTQIPAALSVPEGENLVLNCSFTD...,MLSLLLLLLGLGSVFSAVISQKPSRDICQRGTSLTIQCQVDSQVTM...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVSSQGGSEKLVFTRAV21*01TRAJ57*01CSVDQGGGRMGESY...,162c9435a4fccb0f0718bbc57e1838bb74da39fc01a267...,HLA-A,TCRmodel_no_relax
40169,CAVNSDYKLSF,TRAV1-2*01,TRAJ20*01,CSAGQGPNTGELFF,TRBV20-1*01,TRBJ2-2*01,KLGGALQAK,HLA-A*03:01,B2M,MWGVFLLYVSMKMGGTTGQNIDQPTEMTATEGAIVQINCTYQTSGF...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAVNSDYKLSFTRAV1-2*01TRAJ20*01CSAGQGPNTGELFFTR...,5f41aae24eb1f4ea278ddd757f7eab0a0f741069b5b4b5...,HLA-A,TCRmodel_no_relax
40170,CALIQGAQKLVF,TRAV38-1*01,TRAJ54*01,CASSPATGGHQPQHF,TRBV6-5*01,TRBJ1-5*01,KLGGALQAK,HLA-A*03:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSIGLLCCAALSLLWAGPVNAGVTQTPKFQVLKTGQSMTLQCAQDM...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CALIQGAQKLVFTRAV38-1*01TRAJ54*01CASSPATGGHQPQH...,277403a1734b6a592064ff8120aa0e32c1efbd3d463fa8...,HLA-A,TCRmodel_no_relax
40172,CALSRAGANSKLTF,TRAV9-2*01,TRAJ56*01,CASSPHARDRVRGNTEAFF,TRBV5-1*01,TRBJ1-1*01,KLGGALQAK,HLA-A*03:01,B2M,MNYSPGLVSLILLLLGRTRGNSVTQMEGPVTLSEEAFLTINCTYTA...,MGSRLLCWVLLCLLGAGPVKAGVTQTPRYLIKTRGQQVTLSCSPIS...,HLA-A*03:01,MAVMAPRTLLLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CALSRAGANSKLTFTRAV9-2*01TRAJ56*01CASSPHARDRVRG...,929ebcb427bad25ee226e5b956b9df0b6ea9ef087220d1...,HLA-A,TCRmodel_no_relax

In [32]:
data_to_generate_test = data_to_generate_1.head(5)
data_to_generate_test['hla_gene'] = 'Test'

data_to_generate_test

/scratch/ipykernel_2225045/83883551.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_to_generate_test['hla_gene'] = 'Test'

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,antigen.epitope,mhc.a,mhc.b,TRA_aa_seq,TRB_aa_seq,mhc.a.short,mhc.aa.seq,index_seq,TCR_hash,hla_gene,generation_method
3508,CAGSYGGSQGNLIF,TRAV35*01,TRAJ42*01,CASSVRSSGEQFF,TRBV19*01,TRBJ2-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGSYGGSQGNLIFTRAV35*01TRAJ42*01CASSVRSSGEQFFT...,0b503b58a7567ceeed312bbd3284ea683bfaa3a9134384...,Test,TCRmodel_no_relax
3509,CAGPDGSSNTGKLIF,TRAV35*01,TRAJ37*01,CASSLIFPGRAFF,TRBV27*01,TRBJ1-1*01,GILGFVFTL,HLA-A*02:01,B2M,MLLEHLLIILWMQLTWVSGQQLNQSPQSMFIQEGEDVSMNCTSSSI...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAGPDGSSNTGKLIFTRAV35*01TRAJ37*01CASSLIFPGRAFF...,8676fcdbea24492db07eb1e0b73a923cb490a7ffeae47a...,Test,TCRmodel_no_relax
3510,CAFMVNAGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGSYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAFMVNAGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGSYG...,936577cc40fa11349a5d8a6df30a44c123312d921cd30d...,Test,TCRmodel_no_relax
3511,CAYSPASGGTSYGKLTF,TRAV38-1*01,TRAJ52*01,CASSIGLYGYTF,TRBV19*01,TRBJ1-2*01,GILGFVFTL,HLA-A*02:01,B2M,MTRVSLLWAVVVSTCLESGMAQTVTQSQPEMSVQEAETVTLSCTYD...,MSNQVLCCVVLCFLGANTVDGGITQSPKYLFRKEGQNVTLSCEQNL...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAYSPASGGTSYGKLTFTRAV38-1*01TRAJ52*01CASSIGLYG...,c988791e011fe924c9ace35f30961c5d6152a934d10dea...,Test,TCRmodel_no_relax
3512,CAEDNNARLMF,TRAV5*01,TRAJ31*01,CSARVGVGNTIYF,TRBV20-1*01,TRBJ1-3*01,GLCTLVAML,HLA-A*02:01,B2M,MKTFAGFSFLFLWLQLDCMSRGEDVEQSLFLSVREGDSSVINCTYT...,MLLLLLLLGPGISLLLPGSLAGSGLGAVVSQHPSWVICKSGTSVKI...,HLA-A*02:01,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,CAEDNNARLMFTRAV5*01TRAJ31*01CSARVGVGNTIYFTRBV2...,d0ff9f35e47e8e0d862d9cee9e87a0d30c094524931382...,Test,TCRmodel_no_relax

In [33]:
data_to_generate_test.to_csv('HomoSapiens_MHCI_all_clusters_chunk_test.tsv', sep='\t')

# Table update

In [39]:
table_sent = pd.read_csv('/projects/structures/clusters/data_to_send/final_table_iter_1.tsv', sep='\t', index_col=0)
table_sent

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file,structure_type,confidence
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb,scherbinin,unknown
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb,scherbinin,unknown
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown

In [41]:
table_sent.columns

Index(['cdr3.alpha', 'v.alpha', 'j.alpha', 'cdr3.beta', 'v.beta', 'j.beta',
       'species', 'mhc.a', 'mhc.b', 'antigen.epitope', 'TRA_aa_seq',
       'TRB_aa_seq', 'mhc.a.aa.seq', 'mhc.b.aa.seq', 'pdb_file',
       'structure_type', 'confidence'],
      dtype='object')

In [34]:
import os

In [37]:
files = pd.Series(os.listdir('/projects/structures/clusters/data_to_send/'))

files = files[files.str.endswith('.tsv')]

files

1214    final_table_iter_1.tsv
dtype: object

In [42]:
import hashlib

def hash_string(input_string: str) -> str:
    """
    Computes a SHA-256 hash of the input string and returns it as a hexadecimal string.
    
    This provides a consistent, deterministic hash across different Python runs.
    Note: Python's built-in hash() function is not consistent due to hash randomization.
    
    Args:
        input_string (str): The string to hash.
    
    Returns:
        str: The hexadecimal representation of the hash.
    """
    # Encode the string to bytes
    encoded = input_string.encode('utf-8')
    
    # Create a SHA-256 hash object
    sha256_hash = hashlib.sha256()
    
    # Update the hash object with the encoded string
    sha256_hash.update(encoded)
    
    # Get the hexadecimal digest
    return sha256_hash.hexdigest()

In [44]:
table_sent['index_seq'] = table_sent['cdr3.alpha'] + table_sent['v.alpha'] + table_sent['j.alpha'] + table_sent['cdr3.beta'] + table_sent['v.beta'] + table_sent['j.beta'] + table_sent['mhc.a'] + table_sent['mhc.b'] + table_sent['antigen.epitope'] 

table_sent

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file,structure_type,confidence,index_seq
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown,CAVNRYDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...

In [45]:
table_sent['TCR_hash'] = table_sent.index_seq.apply(lambda x: hash_string(x))

table_sent

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file,structure_type,confidence,index_seq,TCR_hash
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...,20350288084b42c9b68db20e8e8f90466438e3619b6116...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown,CAVNRYDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7a0667b60789d2496b5443b497d6e4b60281b110a79bc9...
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,c08c814fee5d6996d3625ddd1290daa4a0a96ce762c81b...
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,c08c814fee5d6996d3625ddd1290daa4a0a96ce762c81b...
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7dd8e499046c94f1eb25b43c56532b060cddd0cd7dec75...
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7dd8e499046c94f1eb25b43c56532b060cddd0cd7dec75...

In [53]:
generated_structures = pd.Series(os.listdir('/projects/structures/clusters/MHCI_align/contacts_and_skeleton_plots_concated'))

generated_structures_hash = generated_structures.apply(lambda x: x.split('.')[0].split('_')[0]).drop_duplicates()
generated_structures

0        17c67054afa5778b6039bffd31649231edf2f34c24ccfc...
1        a518a51a0c433cc2f75685ecdc8ae50c29db06f8fd93f7...
2        30b6fa655aad61e3e72130d8bbd07eb6a74e2b31dd4883...
3        1f43fabb8bc7f41eaa43c5fc2441a45af7724f303d9fb1...
4        ededda26a8abe73e4bc42d2aa9efd0b5a0ba88ec2bad74...
                               ...
17431    dd94261223abd69c483328f46fa1d8dd1c0ad80d13ded2...
17432    375f23aa3ffe668aef8acb79068110504e4bebbd0e99a6...
17433    f284d226a0055becdd0d6ee6a6525d95bf69aa9801739e...
17434    a8a0910f39b5078974514bee6e9365febd02ef2eb4b026...
17435    9c016fe000d7badf167cceaaa674d7a2e6555c5a9a5442...
Length: 17436, dtype: object

In [68]:
os.listdir('/projects/structures/clusters/MHCI_align/AVFDRKSDAK/')

['aligned_aligned_913968fe816cfcd8c64477d5c6695878daf5698615807448465bd4e0b0e5d8e3.pdb',
 'aligned_aligned_aligned_22ec92fb22ca2c6f5ae8846bf0d560b0799d39b7d66649e1a770c39d01222b1d.pdb',
 'aligned_aligned_f36d9ea139d5fe413a8080453139cde794232ab145f2f6cbd3d6f48cc1699f04.pdb',
 'aligned_aligned_80c36757727d5c2fe58fe6d4c8de0dbc208ed09984d3fb770c8262af08774262.pdb',
 'aligned_aligned_22ec92fb22ca2c6f5ae8846bf0d560b0799d39b7d66649e1a770c39d01222b1d.pdb',
 'aligned_aligned_aligned_80d4b68a396ecbc9924dfa8439bade003a19478a5fb3904bec9d7bc35faff267.pdb',
 'aligned_aligned_aligned_27fa47181cf71c822a6ed947458597d6f9eb64c8fcefd56479552e15b0f35755.pdb',
 'aligned_aligned_bcdb42a7fd17fa4f3258825d1875013432e87958368c7449a2fc1a573e1f100d.pdb',
 'contacts_and_skeleton_plots',
 'aligned_aligned_df269594ce98ef96c2bb99acec23b87d6e289951503c4eb8b8f0628676c3bbcc.pdb',
 'aligned_aligned_aligned_913968fe816cfcd8c64477d5c6695878daf5698615807448465bd4e0b0e5d8e3.pdb',
 'aligned_aligned_aligned_df269594ce98ef96c2bb99acec23b87d6e289951503c4eb8b8f0628676c3bbcc.pdb',
 'aligned_aligned_aligned_99048b427932ad045b403377128168dd55e3a2ffa617c97a9ea96c607cb42017.pdb',
 'aligned_aligned_aligned_80c36757727d5c2fe58fe6d4c8de0dbc208ed09984d3fb770c8262af08774262.pdb',
 'aligned_aligned_80d4b68a396ecbc9924dfa8439bade003a19478a5fb3904bec9d7bc35faff267.pdb',
 'aligned_aligned_58d016c76e1c778fd2e2d2a5600435ada1669a17de9f5a57396562d01c673711.pdb',
 'aligned_aligned_aligned_bcdb42a7fd17fa4f3258825d1875013432e87958368c7449a2fc1a573e1f100d.pdb',
 'aligned_aligned_aligned_58d016c76e1c778fd2e2d2a5600435ada1669a17de9f5a57396562d01c673711.pdb',
 'aligned_aligned_27fa47181cf71c822a6ed947458597d6f9eb64c8fcefd56479552e15b0f35755.pdb',
 'aligned_aligned_99048b427932ad045b403377128168dd55e3a2ffa617c97a9ea96c607cb42017.pdb',
 'aligned_aligned_aligned_f36d9ea139d5fe413a8080453139cde794232ab145f2f6cbd3d6f48cc1699f04.pdb',
 'aligned_aligned_aligned_4e68f3a6877f12a6a83823174a0adf34a6e887179931439a8fb8b456ce11f6d3.pdb',
 'aligned_aligned_4e68f3a6877f12a6a83823174a0adf34a6e887179931439a8fb8b456ce11f6d3.pdb']

In [54]:
generated_structures_hash

0        17c67054afa5778b6039bffd31649231edf2f34c24ccfc...
1        a518a51a0c433cc2f75685ecdc8ae50c29db06f8fd93f7...
2        30b6fa655aad61e3e72130d8bbd07eb6a74e2b31dd4883...
3        1f43fabb8bc7f41eaa43c5fc2441a45af7724f303d9fb1...
4        ededda26a8abe73e4bc42d2aa9efd0b5a0ba88ec2bad74...
                               ...
11512    ad06bfcecc856c3b71ee27e830c0b4a4b5385c2b0f7f9d...
12494    09364a349a8716d3a3e56632777b77973cc5f19b79f3f8...
12631    ad702173608498dbeef6d6d5e5b6bc0a1070cc43780e5e...
12770    b0eb78765cc7e35e441683ad94835b27c935a744a485a7...
12799    2a4990f5564cd5bfb053fac996af0a9c40308d1a292e3c...
Length: 2906, dtype: object

In [58]:
len(set(table_sent.TCR_hash).intersection(set(generated_structures_hash)))

2906

In [61]:
generated_structires_hashes = set(generated_structures_hash)

In [71]:
table_sent.structure_type = table_sent.T.apply(lambda x: 'TCRmodel2' if x.structure_type == 'unmodeled' and x.TCR_hash in generated_structires_hashes else x.structure_type)
table_sent.pdb_file = table_sent.T.apply(lambda x: 'aligned_' + x.TCR_hash + '.pdb' if pd.isnull(x.pdb_file) and x.TCR_hash in generated_structires_hashes else x.pdb_file)

table_sent

,cdr3.alpha,v.alpha,j.alpha,cdr3.beta,v.beta,j.beta,species,mhc.a,mhc.b,antigen.epitope,TRA_aa_seq,TRB_aa_seq,mhc.a.aa.seq,mhc.b.aa.seq,pdb_file,structure_type,confidence,index_seq,TCR_hash
993,CAYRSAGSGGSNYKLTF,TRAV38-2/DV8*01,TRAJ53*01,CASSLMTNQPQHF,TRBV27*01,TRBJ1-5*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAGSGGSNYKLTFTRAV38-2/DV8*01TRAJ53*01CASSL...,41a63492df6bf6860a5bf09d4bda52c94a87c7025fe305...
994,CAYRSATGYALNF,TRAV38-2/DV8*01,TRAJ41*01,CASSLYGSVQNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSATGYALNFTRAV38-2/DV8*01TRAJ41*01CASSLYGSV...,896916807a877df600fa4a72ad2dca40faba11062e38c8...
995,CALSEYSGGYQKVTF,TRAV19*01,TRAJ13*01,CASSVATSGGSQQFF,TRBV9*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MLTASLLRAVIASICVVSSMAQKVTQAQTEISVVEKEDVTLDCVYE...,MGFRLLCCVAFCLLGAGPVDSGVTQTPKHLITATGQRVTLRCSPRS...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CALSEYSGGYQKVTFTRAV19*01TRAJ13*01CASSVATSGGSQQ...,20350288084b42c9b68db20e8e8f90466438e3619b6116...
996,CAVDNYGQNFVF,TRAV41*01,TRAJ26*01,CASSLYGADTQYF,TRBV27*01,TRBJ2-3*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MVKIRQFLLAILWLQLSCVSAAKNEVEQSPQNLTAQEGEFITINCS...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAVDNYGQNFVFTRAV41*01TRAJ26*01CASSLYGADTQYFTRB...,fa037af921d19f11109fac98d1ad9aa01aa523349113eb...
1001,CAYRSAIQDKIIF,TRAV38-2/DV8*01,TRAJ30*01,CASSPHPGTSGGASYNEQFF,TRBV27*01,TRBJ2-1*01,HomoSapiens,HLA-B*07:02,B2M,HPNGYKSLSTL,MACPGFLWALVISTCLEFSMAQTVTQSQPEMSVQEAETVTLSCTYD...,MGPQLLGYVVLCLLGAGPLEAQVTQNPRYLITVTGKKLTVTCSQNM...,MLVMAPRTVLLLLSAALALTETWAGSHSMRYFYTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,NaN,unmodeled,validated,CAYRSAIQDKIIFTRAV38-2/DV8*01TRAJ30*01CASSPHPGT...,91e7bc59620ac613919dfdba0fa0d190a093c8ed12e1c9...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3208,CAVNRYDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1604_repacked.pdb,scherbinin,unknown,CAVNRYDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7a0667b60789d2496b5443b497d6e4b60281b110a79bc9...
3209,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_min.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,c08c814fee5d6996d3625ddd1290daa4a0a96ce762c81b...
3210,CAVNSGDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1605_repacked.pdb,scherbinin,unknown,CAVNSGDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,c08c814fee5d6996d3625ddd1290daa4a0a96ce762c81b...
3211,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_min.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7dd8e499046c94f1eb25b43c56532b060cddd0cd7dec75...
3212,CAVNVDDKIIF,TRAV12-2*01,TRAJ30*01,CASSPDIEQYF,TRBV7-9*01,TRBJ2-7*01,HomoSapiens,HLA-A*02:01,B2M,YLQPRTFLL,MKSLRVLLVILWLQLSWVWSQQKEVEQNSGPLSVPEGAIASLNCTY...,MGTSLLCWMALCLLGADHADTGVSQNPRHKITKRGQNVTFRCDPIS...,MAVMAPRTLVLLLSGALALTQTWAGSHSMRYFFTSVSRPGRGEPRF...,MSRSVALAVLALLSLSGLEAIQHSGLLTSSSREWKVKFPELLCVWV...,VDJdb_Model_1606_repacked.pdb,scherbinin,unknown,CAVNVDDKIIFTRAV12-2*01TRAJ30*01CASSPDIEQYFTRBV...,7dd8e499046c94f1eb25b43c56532b060cddd0cd7dec75...

In [73]:
table_sent.drop('index_seq', axis = 1, inplace=True)

In [75]:
table_sent.to_csv('./final_table_iter_2.tsv', sep='\t',)

In [70]:
import os

# ←←← СЮДА ВПИШИ СВОЙ ПУТЬ ←←←
target_folder = "/projects/structures/clusters/MHCI_align/"

# Нормализуем путь (убираем лишние слеши, кавычки и т.д.)
target_folder = os.path.normpath(target_folder)

if not os.path.isdir(target_folder):
    print(f"Ошибка: папка не найдена → {target_folder}")
    exit()

for root, dirs, files in os.walk(target_folder):
    for filename in files:
        new_name = filename.replace("aligned_aligned_aligned_", "aligned_")
        new_name = new_name.replace("aligned_aligned_", "aligned_")
        
        if new_name != filename:
            old_path = os.path.join(root, filename)
            new_path = os.path.join(root, new_name)
            
            # if os.path.exists(new_path):
            #     print(f"ПРОПУСК (уже существует): {old_path}")
            #     continue
                
            os.rename(old_path, new_path)
            print(f"Переименован: {filename} → {new_name}")

Переименован: aligned_aligned_1f964ecf16c7641fb70268b3a81929167132d1aa2271901043706c574e6b212d.pdb → aligned_1f964ecf16c7641fb70268b3a81929167132d1aa2271901043706c574e6b212d.pdb
Переименован: aligned_aligned_d17c419dd3b4c703a408bc0a2fb839a636319dc664e0f07cdee98c93256a3c5f.pdb → aligned_d17c419dd3b4c703a408bc0a2fb839a636319dc664e0f07cdee98c93256a3c5f.pdb
Переименован: aligned_aligned_aligned_1da6defc19933e04b3e8971f88fa035f9ea069eadfe2c28e16dca311b8138775.pdb → aligned_1da6defc19933e04b3e8971f88fa035f9ea069eadfe2c28e16dca311b8138775.pdb
Переименован: aligned_aligned_53919424bc8f66517fcc537305ac1676c02f854341cc1b0b02b8e0af8a32153c.pdb → aligned_53919424bc8f66517fcc537305ac1676c02f854341cc1b0b02b8e0af8a32153c.pdb
Переименован: aligned_aligned_aligned_5dae275196ef057de45ac3b9eb47d06df063c3c9a7a26738c3a7986fd5653207.pdb → aligned_5dae275196ef057de45ac3b9eb47d06df063c3c9a7a26738c3a7986fd5653207.pdb
Переименован: aligned_aligned_25d9fa6aa4573ccf45ac48e594c83cbb253655b37eada324673e9511a85d3b68.pdb → aligned_25d9fa6aa4573ccf45ac48e594c83cbb253655b37eada324673e9511a85d3b68.pdb
Переименован: aligned_aligned_aligned_f03a959ffd502a1a758fdea7ae17cb4849e223fa7b5d3de76ce63347a743f797.pdb → aligned_f03a959ffd502a1a758fdea7ae17cb4849e223fa7b5d3de76ce63347a743f797.pdb
Переименован: aligned_aligned_aligned_e291427a2762655302fbe5bd98c183ee2823dc0640a71666befc350001978eb8.pdb → aligned_e291427a2762655302fbe5bd98c183ee2823dc0640a71666befc350001978eb8.pdb
Переименован: aligned_aligned_aligned_a01ec2baf2e25304a4a952db5816ad4064ca223ac71f0e9e7993229e5d3f78f6.pdb → aligned_a01ec2baf2e25304a4a952db5816ad4064ca223ac71f0e9e7993229e5d3f78f6.pdb
Переименован: aligned_aligned_39bde144133ce2b81ab6732fd959458e71f3b6a2a512ef5821bef964a6f6640e.pdb → aligned_39bde144133ce2b81ab6732fd959458e71f3b6a2a512ef5821bef964a6f6640e.pdb
Переименован: aligned_aligned_56277871cc237ab84860a9f735838c9c39bd90567d6f0bfe19f1677c32ba0ef1.pdb → aligned_56277871cc237ab84860a9f735838c9c39bd90567d6f0bfe19f1677c32ba0ef1.pdb
Переименован: aligned_aligned_0199264620d50cb1a5fee50502eb8f0cd78c7d2d0c1b57a4a7d37f35845b037a.pdb → aligned_0199264620d50cb1a5fee50502eb8f0cd78c7d2d0c1b57a4a7d37f35845b037a.pdb
Переименован: aligned_aligned_aligned_dfadc8ce782b5acaa6072251a87a7460f5bbf8571067e15abf9845538e4b3d00.pdb → aligned_dfadc8ce782b5acaa6072251a87a7460f5bbf8571067e15abf9845538e4b3d00.pdb
Переименован: aligned_aligned_64afa9cbac522c1778c1666292231aa48e22f71d5b0f7f1325896cb8f749cc13.pdb → aligned_64afa9cbac522c1778c1666292231aa48e22f71d5b0f7f1325896cb8f749cc13.pdb
Переименован: aligned_aligned_aligned_00c7190035930ae3b2c38795137289497c0f77a61c249b2cb1516e1171af68eb.pdb → aligned_00c7190035930ae3b2c38795137289497c0f77a61c249b2cb1516e1171af68eb.pdb
Переименован: aligned_aligned_aligned_4174963b3b017310f7d9eb95d3f563bebb42b1133d6ab127b84aa5a7c6e8f598.pdb → aligned_4174963b3b017310f7d9eb95d3f563bebb42b1133d6ab127b84aa5a7c6e8f598.pdb
Переименован: aligned_aligned_aligned_f3ee8803d4af9e6ddf72e032eb59c24855c418115fa7ba4b4fe0e7c83da180e8.pdb → aligned_f3ee8803d4af9e6ddf72e032eb59c24855c418115fa7ba4b4fe0e7c83da180e8.pdb
Переименован: aligned_aligned_76344f789032dc1679e6df63e4d47cb3ee581499753bee4b0c70f77d2e1d7e27.pdb → aligned_76344f789032dc1679e6df63e4d47cb3ee581499753bee4b0c70f77d2e1d7e27.pdb
Переименован: aligned_aligned_aligned_6cef47003e26ebbdf0eac08c2ab6d7875e71bd96cd26afb6f0c174f7a83c222b.pdb → aligned_6cef47003e26ebbdf0eac08c2ab6d7875e71bd96cd26afb6f0c174f7a83c222b.pdb
Переименован: aligned_aligned_aligned_2e4df0615b6b7e5b111a5297674eaa4dab8ce049f08a1a1dba78b382075c33e0.pdb → aligned_2e4df0615b6b7e5b111a5297674eaa4dab8ce049f08a1a1dba78b382075c33e0.pdb
Переименован: aligned_aligned_071aa65109d2802c6ceaad68bbd968183de780e4fbdc9a47db3ead3dc51c1a79.pdb → aligned_071aa65109d2802c6ceaad68bbd968183de780e4fbdc9a47db3ead3dc51c1a79.pdb
Переименован: aligned_aligned_aligned_cc1d8ae3b4091e43bb65f9cf019b9a865010cb48eb5b8285ba722db5cdcd23c0.pdb → aligned_cc1d8ae3b4091e43bb65f9cf019b9a865010cb48eb5b8285ba722db5cdcd23c0.pdb
Переименован: aligned_aligned_aligned_182ffafc3af8d20d15755bea0322701348f6a0c0bb463fd32f488d3ea5243ecf.pdb → aligned_182ffafc3af8d20d15755bea0322701348f6a0c0bb463fd32f488d3ea5243ecf.pdb
Переименован: aligned_aligned_e291427a2762655302fbe5bd98c183ee2823dc0640a71666befc350001978eb8.pdb → aligned_e291427a2762655302fbe5bd98c183ee2823dc0640a71666befc350001978eb8.pdb
Переименован: aligned_aligned_aligned_07cacdbd3f4dbceb97a828ef7a443c4f0c3207fd6905561fedee241cea63232b.pdb → aligned_07cacdbd3f4dbceb97a828ef7a443c4f0c3207fd6905561fedee241cea63232b.pdb
Переименован: aligned_aligned_a9be5da48432ac0c4339c8be6d269faa183c452b3d127df31119f09cf72046a2.pdb → aligned_a9be5da48432ac0c4339c8be6d269faa183c452b3d127df31119f09cf72046a2.pdb
Переименован: aligned_aligned_aligned_64afa9cbac522c1778c1666292231aa48e22f71d5b0f7f1325896cb8f749cc13.pdb → aligned_64afa9cbac522c1778c1666292231aa48e22f71d5b0f7f1325896cb8f749cc13.pdb
Переименован: aligned_aligned_f3ee8803d4af9e6ddf72e032eb59c24855c418115fa7ba4b4fe0e7c83da180e8.pdb → aligned_f3ee8803d4af9e6ddf72e032eb59c24855c418115fa7ba4b4fe0e7c83da180e8.pdb
Переименован: aligned_aligned_aligned_344cfa121f4a30caf098eacd61d998a307b81186789eed2bc3c63710be41fdae.pdb → aligned_344cfa121f4a30caf098eacd61d998a307b81186789eed2bc3c63710be41fdae.pdb
Переименован: aligned_aligned_aligned_071aa65109d2802c6ceaad68bbd968183de780e4fbdc9a47db3ead3dc51c1a79.pdb → aligned_071aa65109d2802c6ceaad68bbd968183de780e4fbdc9a47db3ead3dc51c1a79.pdb
Переименован: aligned_aligned_72d23af26ea3aef0eff50c2748973a017e9a8a4b724dd1e31038f4cc9cb19a00.pdb → aligned_72d23af26ea3aef0eff50c2748973a017e9a8a4b724dd1e31038f4cc9cb19a00.pdb
Переименован: aligned_aligned_aligned_07e5cf0312b1e4623b66c42c27514272b3aa74e12cb3980acf15717d8169505d.pdb → aligned_07e5cf0312b1e4623b66c42c27514272b3aa74e12cb3980acf15717d8169505d.pdb
Переименован: aligned_aligned_aligned_76f050a5eef135bd6d9832fe61f5fab8d9565ed0699b7ff88d868be0ae43078e.pdb → aligned_76f050a5eef135bd6d9832fe61f5fab8d9565ed0699b7ff88d868be0ae43078e.pdb
Переименован: aligned_aligned_ba91e31b618ce9f7ff17356508942d70d32ef02f55ad5c39fe63230f06086333.pdb → aligned_ba91e31b618ce9f7ff17356508942d70d32ef02f55ad5c39fe63230f06086333.pdb
Переименован: aligned_aligned_5dae275196ef057de45ac3b9eb47d06df063c3c9a7a26738c3a7986fd5653207.pdb → aligned_5dae275196ef057de45ac3b9eb47d06df063c3c9a7a26738c3a7986fd5653207.pdb
Переименован: aligned_aligned_aligned_aabfae43e66fd106d88ad64c603c43a7ccc9923c184d123f278d700ce7ec65e2.pdb → aligned_aabfae43e66fd106d88ad64c603c43a7ccc9923c184d123f278d700ce7ec65e2.pdb
Переименован: aligned_aligned_aligned_39bde144133ce2b81ab6732fd959458e71f3b6a2a512ef5821bef964a6f6640e.pdb → aligned_39bde144133ce2b81ab6732fd959458e71f3b6a2a512ef5821bef964a6f6640e.pdb
Переименован: aligned_aligned_2034ed9d2525fc9297fd3df98a99dbf04eab595a44c2c6d51b004e766274f5c0.pdb → aligned_2034ed9d2525fc9297fd3df98a99dbf04eab595a44c2c6d51b004e766274f5c0.pdb
Переименован: aligned_aligned_aligned_ba91e31b618ce9f7ff17356508942d70d32ef02f55ad5c39fe63230f06086333.pdb → aligned_ba91e31b618ce9f7ff17356508942d70d32ef02f55ad5c39fe63230f06086333.pdb
Переименован: aligned_aligned_aligned_f8e225ff70a736f2bcacdac3fbb29e536f5f025f1f0316e51f57565545bb4315.pdb → aligned_f8e225ff70a736f2bcacdac3fbb29e536f5f025f1f0316e51f57565545bb4315.pdb
Переименован: aligned_aligned_aligned_24cae4b35e91b1c956760f86e2a6a3729d65798cf00f4226509cf11959074981.pdb → aligned_24cae4b35e91b1c956760f86e2a6a3729d65798cf00f4226509cf11959074981.pdb
Переименован: aligned_aligned_58be57270355dea28122861ad7d6adce39c3ceeacfe904111ad60f9ee68c7c37.pdb → aligned_58be57270355dea28122861ad7d6adce39c3ceeacfe904111ad60f9ee68c7c37.pdb
Переименован: aligned_aligned_aligned_80a2b4a58905851dbe0094cd3d3798b01eb8863a5c08f7eb314d7ce74e50544d.pdb → aligned_80a2b4a58905851dbe0094cd3d3798b01eb8863a5c08f7eb314d7ce74e50544d.pdb
Переименован: aligned_aligned_aligned_25d9fa6aa4573ccf45ac48e594c83cbb253655b37eada324673e9511a85d3b68.pdb → aligned_25d9fa6aa4573ccf45ac48e594c83cbb253655b37eada324673e9511a85d3b68.pdb
Переименован: aligned_aligned_aligned_b990fc2379eec3ab36a46fbb493b66f5335119cdd6f5ee0371b3242ea05dd4f6.pdb → aligned_b990fc2379eec3ab36a46fbb493b66f5335119cdd6f5ee0371b3242ea05dd4f6.pdb
Переименован: aligned_aligned_182ffafc3af8d20d15755bea0322701348f6a0c0bb463fd32f488d3ea5243ecf.pdb → aligned_182ffafc3af8d20d15755bea0322701348f6a0c0bb463fd32f488d3ea5243ecf.pdb
Переименован: aligned_aligned_2e4df0615b6b7e5b111a5297674eaa4dab8ce049f08a1a1dba78b382075c33e0.pdb → aligned_2e4df0615b6b7e5b111a5297674eaa4dab8ce049f08a1a1dba78b382075c33e0.pdb
Переименован: aligned_aligned_aligned_b18e4e1f6a0b68de750ff5e9966ffa92acadbcaabeeda1fd6582a4ea86ce8158.pdb → aligned_b18e4e1f6a0b68de750ff5e9966ffa92acadbcaabeeda1fd6582a4ea86ce8158.pdb
Переименован: aligned_aligned_6cef47003e26ebbdf0eac08c2ab6d7875e71bd96cd26afb6f0c174f7a83c222b.pdb → aligned_6cef47003e26ebbdf0eac08c2ab6d7875e71bd96cd26afb6f0c174f7a83c222b.pdb
Переименован: aligned_aligned_aligned_986b9d02888b193f845eb2e875830fb521f104a041d18b6c77c4a84cd948e305.pdb → aligned_986b9d02888b193f845eb2e875830fb521f104a041d18b6c77c4a84cd948e305.pdb
Переименован: aligned_aligned_b42516ec40ef127703bd77d59604029a8fd4cf4281ba43629f2c494071d483f2.pdb → aligned_b42516ec40ef127703bd77d59604029a8fd4cf4281ba43629f2c494071d483f2.pdb
Переименован: aligned_aligned_aligned_2034ed9d2525fc9297fd3df98a99dbf04eab595a44c2c6d51b004e766274f5c0.pdb → aligned_2034ed9d2525fc9297fd3df98a99dbf04eab595a44c2c6d51b004e766274f5c0.pdb
Переименован: aligned_aligned_0b8a1fac1ae61d8b61775d960c133dcc107d025235e0310cca791b73f52c62e3.pdb → aligned_0b8a1fac1ae61d8b61775d960c133dcc107d025235e0310cca791b73f52c62e3.pdb
Переименован: aligned_aligned_b990fc2379eec3ab36a46fbb493b66f5335119cdd6f5ee0371b3242ea05dd4f6.pdb → aligned_b990fc2379eec3ab36a46fbb493b66f5335119cdd6f5ee0371b3242ea05dd4f6.pdb
Переименован: aligned_aligned_aligned_5bbd78d53184d5796aa053f6baba4bb074cf4bf99eafcf9133a5d7847275b833.pdb → aligned_5bbd78d53184d5796aa053f6baba4bb074cf4bf99eafcf9133a5d7847275b833.pdb
Переименован: aligned_aligned_6ba3cd55fd374506f5cbef186315c5f3b02bdab67a75ea5b61eccbfc56398f64.pdb → aligned_6ba3cd55fd374506f5cbef186315c5f3b02bdab67a75ea5b61eccbfc56398f64.pdb
Переименован: aligned_aligned_aligned_a3ec2320b8eafdce195cd85d30f5f03d8793b5de7547e7476c94786fc5173657.pdb → aligned_a3ec2320b8eafdce195cd85d30f5f03d8793b5de7547e7476c94786fc5173657.pdb
Переименован: aligned_aligned_a3ec2320b8eafdce195cd85d30f5f03d8793b5de7547e7476c94786fc5173657.pdb → aligned_a3ec2320b8eafdce195cd85d30f5f03d8793b5de7547e7476c94786fc5173657.pdb
Переименован: aligned_aligned_aligned_17ed18359e281e33a1232bbf5a15088719c68a9cce1e0392887f8fb759060813.pdb → aligned_17ed18359e281e33a1232bbf5a15088719c68a9cce1e0392887f8fb759060813.pdb
Переименован: aligned_aligned_52f7ef9237a905eda472a8f5de6de590f8ca28b9e844a258a7ac961d0acce32f.pdb → aligned_52f7ef9237a905eda472a8f5de6de590f8ca28b9e844a258a7ac961d0acce32f.pdb
Переименован: aligned_aligned_90f340d4a839108b553ee5e6e351e574070ecb7c77ec881c1359f507d76270b2.pdb → aligned_90f340d4a839108b553ee5e6e351e574070ecb7c77ec881c1359f507d76270b2.pdb
Переименован: aligned_aligned_aligned_76fd2999937eb151522013749ca96b2fd70644567a6cfd07805bcd5dc048c0c6.pdb → aligned_76fd2999937eb151522013749ca96b2fd70644567a6cfd07805bcd5dc048c0c6.pdb
Переименован: aligned_aligned_aligned_889cbf586750fb62a308bd32a8b41814555718a465358e4e6bd8b6591676ea3c.pdb → aligned_889cbf586750fb62a308bd32a8b41814555718a465358e4e6bd8b6591676ea3c.pdb
Переименован: aligned_aligned_1da6defc19933e04b3e8971f88fa035f9ea069eadfe2c28e16dca311b8138775.pdb → aligned_1da6defc19933e04b3e8971f88fa035f9ea069eadfe2c28e16dca311b8138775.pdb
Переименован: aligned_aligned_aligned_d686253fd9dee2bd3efd89020c194ad53d8611ce2dcacb87e40d889af6df8d83.pdb → aligned_d686253fd9dee2bd3efd89020c194ad53d8611ce2dcacb87e40d889af6df8d83.pdb
Переименован: aligned_aligned_4174963b3b017310f7d9eb95d3f563bebb42b1133d6ab127b84aa5a7c6e8f598.pdb → aligned_4174963b3b017310f7d9eb95d3f563bebb42b1133d6ab127b84aa5a7c6e8f598.pdb
Переименован: aligned_aligned_a01ec2baf2e25304a4a952db5816ad4064ca223ac71f0e9e7993229e5d3f78f6.pdb → aligned_a01ec2baf2e25304a4a952db5816ad4064ca223ac71f0e9e7993229e5d3f78f6.pdb
Переименован: aligned_aligned_b18e4e1f6a0b68de750ff5e9966ffa92acadbcaabeeda1fd6582a4ea86ce8158.pdb → aligned_b18e4e1f6a0b68de750ff5e9966ffa92acadbcaabeeda1fd6582a4ea86ce8158.pdb
Переименован: aligned_aligned_aligned_72d23af26ea3aef0eff50c2748973a017e9a8a4b724dd1e31038f4cc9cb19a00.pdb → aligned_72d23af26ea3aef0eff50c2748973a017e9a8a4b724dd1e31038f4cc9cb19a00.pdb
Переименован: aligned_aligned_232c260b6b567fdddb211e26ea9132016d297549e0a96521d520082eb827f682.pdb → aligned_232c260b6b567fdddb211e26ea9132016d297549e0a96521d520082eb827f682.pdb
Переименован: aligned_aligned_f8e225ff70a736f2bcacdac3fbb29e536f5f025f1f0316e51f57565545bb4315.pdb → aligned_f8e225ff70a736f2bcacdac3fbb29e536f5f025f1f0316e51f57565545bb4315.pdb
Переименован: aligned_aligned_00c7190035930ae3b2c38795137289497c0f77a61c249b2cb1516e1171af68eb.pdb → aligned_00c7190035930ae3b2c38795137289497c0f77a61c249b2cb1516e1171af68eb.pdb
Переименован: aligned_aligned_aligned_d709b2eaa588c55b2c8bb819a91487b3cdbcaa4901cd6a159967e6f3ade93cd0.pdb → aligned_d709b2eaa588c55b2c8bb819a91487b3cdbcaa4901cd6a159967e6f3ade93cd0.pdb
Переименован: aligned_aligned_aligned_6fadcc08353a0aaafc3cd8964a75f09ff928b35469a7618494578918ec4efe6b.pdb → aligned_6fadcc08353a0aaafc3cd8964a75f09ff928b35469a7618494578918ec4efe6b.pdb
Переименован: aligned_aligned_aligned_168a3b89bd959855bdfbc6a1b43371407048f65f395d6957f060bbb57a431aa4.pdb → aligned_168a3b89bd959855bdfbc6a1b43371407048f65f395d6957f060bbb57a431aa4.pdb
Переименован: aligned_aligned_aligned_91dcc9cb7ab88a93ce4d9964aa2d53c59eb726e3f11c87b647300f0c2b04099a.pdb → aligned_91dcc9cb7ab88a93ce4d9964aa2d53c59eb726e3f11c87b647300f0c2b04099a.pdb
Переименован: aligned_aligned_aligned_0d513aff90c802ac813fc375f08b595bf51501a04821b2b0bf7ed4a67b28a155.pdb → aligned_0d513aff90c802ac813fc375f08b595bf51501a04821b2b0bf7ed4a67b28a155.pdb
Переименован: aligned_aligned_aligned_68bc1e5bc9c2e7beaa07a80b815cda19da558d940419fcf41a654a4f0a84a546.pdb → aligned_68bc1e5bc9c2e7beaa07a80b815cda19da558d940419fcf41a654a4f0a84a546.pdb
Переименован: aligned_aligned_aligned_fbc1776bbf9be6c95ff105961c00ffef863ac36f62e44e80fea18a353c33b230.pdb → aligned_fbc1776bbf9be6c95ff105961c00ffef863ac36f62e44e80fea18a353c33b230.pdb
Переименован: aligned_aligned_573d6d58186e937d3137ed96e67e28e08b5db9d6811d2b574e98d906a686aeae.pdb → aligned_573d6d58186e937d3137ed96e67e28e08b5db9d6811d2b574e98d906a686aeae.pdb
Переименован: aligned_aligned_aligned_2d57d01eb95b5924737d37d45b3e98a371beea6aa47ecb66021480a76756e438.pdb → aligned_2d57d01eb95b5924737d37d45b3e98a371beea6aa47ecb66021480a76756e438.pdb
Переименован: aligned_aligned_aligned_d17c419dd3b4c703a408bc0a2fb839a636319dc664e0f07cdee98c93256a3c5f.pdb → aligned_d17c419dd3b4c703a408bc0a2fb839a636319dc664e0f07cdee98c93256a3c5f.pdb
Переименован: aligned_aligned_aligned_58be57270355dea28122861ad7d6adce39c3ceeacfe904111ad60f9ee68c7c37.pdb → aligned_58be57270355dea28122861ad7d6adce39c3ceeacfe904111ad60f9ee68c7c37.pdb
Переименован: aligned_aligned_aligned_1a407b768f49a878688a3e2e5931e17a49e80e8921b68ae2a0859c230d8df1b1.pdb → aligned_1a407b768f49a878688a3e2e5931e17a49e80e8921b68ae2a0859c230d8df1b1.pdb
Переименован: aligned_aligned_aligned_a9be5da48432ac0c4339c8be6d269faa183c452b3d127df31119f09cf72046a2.pdb → aligned_a9be5da48432ac0c4339c8be6d269faa183c452b3d127df31119f09cf72046a2.pdb
Переименован: aligned_aligned_aligned_6ba3cd55fd374506f5cbef186315c5f3b02bdab67a75ea5b61eccbfc56398f64.pdb → aligned_6ba3cd55fd374506f5cbef186315c5f3b02bdab67a75ea5b61eccbfc56398f64.pdb
Переименован: aligned_aligned_6fadcc08353a0aaafc3cd8964a75f09ff928b35469a7618494578918ec4efe6b.pdb → aligned_6fadcc08353a0aaafc3cd8964a75f09ff928b35469a7618494578918ec4efe6b.pdb
Переименован: aligned_aligned_aligned_1203107fd04b78e9a184a15bdcfed98175cd0b52e1c98e3dc0e634a99add5a1a.pdb → aligned_1203107fd04b78e9a184a15bdcfed98175cd0b52e1c98e3dc0e634a99add5a1a.pdb
Переименован: aligned_aligned_344cfa121f4a30caf098eacd61d998a307b81186789eed2bc3c63710be41fdae.pdb → aligned_344cfa121f4a30caf098eacd61d998a307b81186789eed2bc3c63710be41fdae.pdb
Переименован: aligned_aligned_aligned_0b8a1fac1ae61d8b61775d960c133dcc107d025235e0310cca791b73f52c62e3.pdb → aligned_0b8a1fac1ae61d8b61775d960c133dcc107d025235e0310cca791b73f52c62e3.pdb
Переименован: aligned_aligned_aligned_53919424bc8f66517fcc537305ac1676c02f854341cc1b0b02b8e0af8a32153c.pdb → aligned_53919424bc8f66517fcc537305ac1676c02f854341cc1b0b02b8e0af8a32153c.pdb
Переименован: aligned_aligned_76fd2999937eb151522013749ca96b2fd70644567a6cfd07805bcd5dc048c0c6.pdb → aligned_76fd2999937eb151522013749ca96b2fd70644567a6cfd07805bcd5dc048c0c6.pdb
Переименован: aligned_aligned_80a2b4a58905851dbe0094cd3d3798b01eb8863a5c08f7eb314d7ce74e50544d.pdb → aligned_80a2b4a58905851dbe0094cd3d3798b01eb8863a5c08f7eb314d7ce74e50544d.pdb
Переименован: aligned_aligned_899501b9ce86496cc54c89dddd3304ad90a55331a29fe13434884c9c54708171.pdb → aligned_899501b9ce86496cc54c89dddd3304ad90a55331a29fe13434884c9c54708171.pdb
Переименован: aligned_aligned_aligned_0199264620d50cb1a5fee50502eb8f0cd78c7d2d0c1b57a4a7d37f35845b037a.pdb → aligned_0199264620d50cb1a5fee50502eb8f0cd78c7d2d0c1b57a4a7d37f35845b037a.pdb
Переименован: aligned_aligned_5bbd78d53184d5796aa053f6baba4bb074cf4bf99eafcf9133a5d7847275b833.pdb → aligned_5bbd78d53184d5796aa053f6baba4bb074cf4bf99eafcf9133a5d7847275b833.pdb
Переименован: aligned_aligned_aligned_76344f789032dc1679e6df63e4d47cb3ee581499753bee4b0c70f77d2e1d7e27.pdb → aligned_76344f789032dc1679e6df63e4d47cb3ee581499753bee4b0c70f77d2e1d7e27.pdb
Переименован: aligned_aligned_aligned_56277871cc237ab84860a9f735838c9c39bd90567d6f0bfe19f1677c32ba0ef1.pdb → aligned_56277871cc237ab84860a9f735838c9c39bd90567d6f0bfe19f1677c32ba0ef1.pdb
Переименован: aligned_aligned_07e5cf0312b1e4623b66c42c27514272b3aa74e12cb3980acf15717d8169505d.pdb → aligned_07e5cf0312b1e4623b66c42c27514272b3aa74e12cb3980acf15717d8169505d.pdb
Переименован: aligned_aligned_f03a959ffd502a1a758fdea7ae17cb4849e223fa7b5d3de76ce63347a743f797.pdb → aligned_f03a959ffd502a1a758fdea7ae17cb4849e223fa7b5d3de76ce63347a743f797.pdb
Переименован: aligned_aligned_aligned_7fe415b22eb1b0b088bb18c0c04f486e9e7d2140f964f003d3d4216df1b60b96.pdb → aligned_7fe415b22eb1b0b088bb18c0c04f486e9e7d2140f964f003d3d4216df1b60b96.pdb
Переименован: aligned_aligned_889cbf586750fb62a308bd32a8b41814555718a465358e4e6bd8b6591676ea3c.pdb → aligned_889cbf586750fb62a308bd32a8b41814555718a465358e4e6bd8b6591676ea3c.pdb
Переименован: aligned_aligned_1a407b768f49a878688a3e2e5931e17a49e80e8921b68ae2a0859c230d8df1b1.pdb → aligned_1a407b768f49a878688a3e2e5931e17a49e80e8921b68ae2a0859c230d8df1b1.pdb
Переименован: aligned_aligned_cc1d8ae3b4091e43bb65f9cf019b9a865010cb48eb5b8285ba722db5cdcd23c0.pdb → aligned_cc1d8ae3b4091e43bb65f9cf019b9a865010cb48eb5b8285ba722db5cdcd23c0.pdb
Переименован: aligned_aligned_24cae4b35e91b1c956760f86e2a6a3729d65798cf00f4226509cf11959074981.pdb → aligned_24cae4b35e91b1c956760f86e2a6a3729d65798cf00f4226509cf11959074981.pdb
Переименован: aligned_aligned_07cacdbd3f4dbceb97a828ef7a443c4f0c3207fd6905561fedee241cea63232b.pdb → aligned_07cacdbd3f4dbceb97a828ef7a443c4f0c3207fd6905561fedee241cea63232b.pdb
Переименован: aligned_aligned_986b9d02888b193f845eb2e875830fb521f104a041d18b6c77c4a84cd948e305.pdb → aligned_986b9d02888b193f845eb2e875830fb521f104a041d18b6c77c4a84cd948e305.pdb
Переименован: aligned_aligned_fbc1776bbf9be6c95ff105961c00ffef863ac36f62e44e80fea18a353c33b230.pdb → aligned_fbc1776bbf9be6c95ff105961c00ffef863ac36f62e44e80fea18a353c33b230.pdb
Переименован: aligned_aligned_91dcc9cb7ab88a93ce4d9964aa2d53c59eb726e3f11c87b647300f0c2b04099a.pdb → aligned_91dcc9cb7ab88a93ce4d9964aa2d53c59eb726e3f11c87b647300f0c2b04099a.pdb

In [60]:
table_sent.structure_type.unique()

array(['unmodeled', 'TCRmodel2', 'native', 'scherbinin'], dtype=object)

In [65]:
table_sent.structure_type.value_counts()

structure_type
unmodeled     75216
TCRmodel2      4714
scherbinin     3211
native          261
Name: count, dtype: int64